<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <div class="msg"><?= $this->message ?></div>
                        <? } ?>
<script type="text/javascript">
    YAHOO.namespace("local.calendar");

    YAHOO.local.calendar.init = function()
    {
        var eLog = YAHOO.util.Dom.get("evtentries");

        YAHOO.local.calendar.fechaIngreso = new YAHOO.widget.Calendar("fechaIngreso","calFechaIngreso");
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.fechaIngreso.selectEvent.subscribe(handlerCalFechaIngresoES,
                YAHOO.local.calendar.fechaIngreso, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.fechaIngreso.selectEvent.subscribe(handlerCalFechaIngresoEN,
                YAHOO.local.calendar.fechaIngreso, true);
        <? } ?>

        YAHOO.local.calendar.fechaIngreso.render();

// vencimiento

        YAHOO.local.calendar.vencimiento = new YAHOO.widget.Calendar("idVencimiento","calVencimiento");
        YAHOO.local.calendar.vencimiento.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.vencimiento.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.vencimiento.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.vencimiento.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.vencimiento.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.vencimiento.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.vencimiento.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.vencimiento.selectEvent.subscribe(handlerCalvencimientoES,
                YAHOO.local.calendar.vencimiento, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.vencimiento.selectEvent.subscribe(handlerCalvencimientoEN,
                YAHOO.local.calendar.vencimiento, true);
        <? } ?>

        YAHOO.local.calendar.vencimiento.render();


// ingresoPuerto

        YAHOO.local.calendar.ingresoPuerto = new YAHOO.widget.Calendar("idIngPuerto","calIngPuerto");
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.ingresoPuerto.selectEvent.subscribe(handlerCalingresoPuertoES,
                YAHOO.local.calendar.ingresoPuerto, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.ingresoPuerto.selectEvent.subscribe(handlerCalingresoPuertoEN,
                YAHOO.local.calendar.ingresoPuerto, true);
        <? } ?>

        YAHOO.local.calendar.ingresoPuerto.render();


// PERpresentado
        YAHOO.local.calendar.perpre = new YAHOO.widget.Calendar("idPerPre","calPerPre");
        YAHOO.local.calendar.perpre.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.perpre.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.perpre.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.perpre.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.perpre.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.perpre.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.perpre.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.perpre.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.perpre.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.perpre.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.perpre.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.perpre.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.perpre.selectEvent.subscribe(handlerCalperpreES,
                YAHOO.local.calendar.perpre, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.perpre.selectEvent.subscribe(handlerCalperpreEN,
                YAHOO.local.calendar.perpre, true);
        <? } ?>

        YAHOO.local.calendar.perpre.render();



// idPerFecFac
        YAHOO.local.calendar.fecfac = new YAHOO.widget.Calendar("idPerFecFac","calFecFac");
        YAHOO.local.calendar.fecfac.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.fecfac.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.fecfac.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.fecfac.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.fecfac.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.fecfac.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.fecfac.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.fecfac.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.fecfac.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.fecfac.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.fecfac.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.fecfac.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.fecfac.selectEvent.subscribe(handlerCalfecfacES,
                YAHOO.local.calendar.fecfac, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.fecfac.selectEvent.subscribe(handlerCalfecfacEN,
                YAHOO.local.calendar.fecfac, true);
        <? } ?>

        YAHOO.local.calendar.fecfac.render();


    }

    YAHOO.util.Event.onDOMReady(YAHOO.local.calendar.init);
</script>


<div style="clear:both"></div>
<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<div class="cformulario">
	<?= $this->exportacionAddForm ?>
</div>
<div id="calFechaIngreso" style="display:none;" class="ccalfechaingreso"></div>
<div id="calVencimiento" style="display:none;" class="ccalvencimiento"></div>
<div id="calIngPuerto" style="display:none;" class="ccalingpuerto"></div>
<div id="calPerPre" style="display:none;" class="ccalperpre"></div>
<div id="calFecFac" style="display:none;" class="ccalfecfac"></div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
        var mySchema = ["Resultset.Result","data","id"];
		
		// banderas
        var dataBanderas = new YAHOO.widget.DS_XHR("/user/banderas/getdata/", mySchema);
        dataBanderas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteBanderas = new YAHOO.widget.AutoComplete("idnameBandera", "idbanderasautocomplete", dataBanderas);
        function fnCallback(e, args) {
            YAHOO.util.Dom.get("idcodBandera").value = args[2][1];
         }
        autocompleteBanderas.itemSelectEvent.subscribe(fnCallback);
		
		// transportes
		var dataTransportes = new YAHOO.widget.DS_XHR("/user/transportes/getdata/", mySchema);
        dataTransportes.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteTransportes = new YAHOO.widget.AutoComplete("idnameTransporte", "idtransportesautocomplete", dataTransportes);
        function fnCallbackTrans(e, args) {
            YAHOO.util.Dom.get("idcodTransporte").value = args[2][1];
         }
        autocompleteTransportes.itemSelectEvent.subscribe(fnCallbackTrans);
		
		// clientes
		var dataClientes = new YAHOO.widget.DS_XHR("/user/clientes/getdata/", mySchema);
        dataClientes.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteClientes = new YAHOO.widget.AutoComplete("idnameCliente", "idclientesautocomplete", dataClientes);
        function fnCallbackClie(e, args) {
            YAHOO.util.Dom.get("idcodCliente").value = args[2][1];
         }
        autocompleteClientes.itemSelectEvent.subscribe(fnCallbackClie);

		// monedas
		var dataMonedas = new YAHOO.widget.DS_XHR("/user/monedas/getdata/", mySchema);
        dataMonedas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteMonedas = new YAHOO.widget.AutoComplete("idnameMoneda", "idmonedasautocomplete", dataMonedas);
        function fnCallbackMone(e, args) {
            YAHOO.util.Dom.get("idcodMoneda").value = args[2][1];
         }
        autocompleteMonedas.itemSelectEvent.subscribe(fnCallbackMone);
		
		// cargas
		var dataCargas = new YAHOO.widget.DS_XHR("/user/cargas/getdata/", mySchema);
        dataCargas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteCargas = new YAHOO.widget.AutoComplete("idnameCarga", "idcargasautocomplete", dataCargas);
        function fnCallbackCarg(e, args) {
            YAHOO.util.Dom.get("idcodCarga").value = args[2][1];
         }
        autocompleteCargas.itemSelectEvent.subscribe(fnCallbackCarg);
		
		// destinaciones
		var dataDestinaciones = new YAHOO.widget.DS_XHR("/user/destinaciones/getdata/", mySchema);
        dataDestinaciones.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteDestinaciones = new YAHOO.widget.AutoComplete("idnameDestinacion", "iddestautocomplete", dataDestinaciones);
        function fnCallbackDest(e, args) {
            YAHOO.util.Dom.get("idcodDestinacion").value = args[2][1];
         }
        autocompleteDestinaciones.itemSelectEvent.subscribe(fnCallbackDest);
		
        // validacion
        var frmvalidator  = new Validator("form");

        //habilito alert con mensajes
        frmvalidator.EnableOnPageErrorDisplaySingleBox();
        frmvalidator.EnableMsgsTogether();
        
        frmvalidator.addValidation("orden","req","<?= $this->language->_("*Ingrese el número de órden")?> ");
        frmvalidator.addValidation("orden","numeric","<?= $this->language->_("*La órden debe ser únicamente númerica")?>");
                            
        frmvalidator.addValidation("nameTransporte","req","<?= $this->language->_("*Elija un transporte")?>");
        frmvalidator.addValidation("nameTransporte","alnum_s ","<?= $this->language->_("*El transporte debe ser alfanumérico")?>");
                            
        frmvalidator.addValidation("nameCliente","req","<?= $this->language->_("*Elija un cliente")?>");
        frmvalidator.addValidation("nameCliente","alpha_s","<?= $this->language->_("*El cliente debe ser alfanumérico")?>");

        frmvalidator.addValidation("nameBandera","req","<?= $this->language->_("*Elija una Bandera")?>");
        frmvalidator.addValidation("nameBandera","alpha_s","<?= $this->language->_("*La bandera debe contener sólo letras")?>");

        frmvalidator.addValidation("nameMoneda","req","<?= $this->language->_("*Elija una moneda")?>");
        frmvalidator.addValidation("nameMoneda","alpha_s","<?= $this->language->_("*La moneda debe contener sólo letras")?>");

        frmvalidator.addValidation("nameDestinacion","req","<?= $this->language->_("*Elija una destinación")?>");
        frmvalidator.addValidation("nameDestinacion","alpha_s","<?= $this->language->_("*La destinación debe contener sólo letras")?>");

        frmvalidator.addValidation("nameCarga","req","<?= $this->language->_("*Elija una carga")?>");
        frmvalidator.addValidation("nameCarga","alnum","<?= $this->language->_("*La carga debe contener sólo letras")?>");

        frmvalidator.addValidation("referencia","alnum_s","<?= $this->language->_("*La referencia debe ser alfanumérica")?>");

        frmvalidator.addValidation("fechaIngreso","req","<?= $this->language->_("*Ingrese una fecha de ingreso")?>");
        frmvalidator.addValidation("fechaIngreso","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$", "<?= $this->language->_("*La fecha de ingreso es inválida")?>");

        frmvalidator.addValidation("desMercaderias","req","<?= $this->language->_("*Ingrese una descripción de mercadería")?>");
        frmvalidator.addValidation("desMercaderias","alnum_s","<?= $this->language->_("*La descripción de mercadería debe ser alfanumérica")?>");

        frmvalidator.addValidation("valorFactura","num","<?= $this->language->_("*El valor de factura debe ser numérico")?>");

        frmvalidator.addValidation("vencimiento","req","<?= $this->language->_("*Ingrese un vencimiento")?>");
        frmvalidator.addValidation("vencimiento","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$", "<?= $this->language->_("*La fecha de vencimiento es inválida")?>");

        frmvalidator.addValidation("PERnroDoc","req","<?= $this->language->_("*Ingrese un número de permiso")?>");
        frmvalidator.addValidation("PERnroDoc","num","<?= $this->language->_("*El número de permiso debe ser numérico")?>");
        
        frmvalidator.addValidation("PERpresentado","req","<?= $this->language->_("*Ingrese la fecha del permiso presentado")?>");
        frmvalidator.addValidation("PERpresentado","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha del permiso presentado es inválida")?>");

        frmvalidator.addValidation("PERfactura","alnum_s","<?= $this->language->_("*El permiso de factura debe ser alfanumérico")?>");

        frmvalidator.addValidation("PERfechaFactura","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha de la fecha del permiso de factura es inválida")?>");
		

</script>
