<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <div class="msg"><?= $this->message ?></div>
<? } ?>
<div id="divstat"></div>
<script language="JavaScript" type="text/javascript">
        YAHOO.namespace("stat.container");

        YAHOO.stat.container.panel = new YAHOO.widget.Panel("divstat",
        {   width:"620px", 
            modal:true,
            visible:true, 
            underlay:"shadow",
            fixedcenter:true, 
            constraintoviewport:true, 
            draggable:false
        } );
	YAHOO.stat.container.panel.setHeader("Estadisticas");
	YAHOO.stat.container.panel.setBody("<embed width='600' height='400' bgcolor='#8888bb' src='/charts/charts.swf' FlashVars='library_path=/charts/charts_library&xml_source=/xml/expo_<?=$this->type?>.xml' wmode='opaque' scale='noScale' name='charts' menu='true' allowFullScreen='true' allowScriptAccess='sameDomain' quality='high' pluginspage='http://www.macromedia.com/go/getflashplayer' align='middle' play='true' devicefont='false' salign='TL' type='application/x-shockwave-flash' > </embed>");
	YAHOO.stat.container.panel.setFooter("Trifiori");

    YAHOO.stat.container.panel.render();

</script>
Estadisticas

Exportaciones por pais
exportaciones por destinacion
exportaciones por cliente
exportaciones por 

