<script type="text/javascript">
var myColumnDefs =
	[{key:"orden",label:" <?= $this->language->_("Orden")?> ", sortable:true},
	{key:"trans",label:" <?= $this->language->_("Transporte")?> ", sortable:true},
	{key:"cliente",label:" <?= $this->language->_("Codigo Cliente")?> ", sortable:true},
	{key:"destinacion",label:" <?= $this->language->_("Destinación")?> ", sortable:true},
	{key:"carga",label:" <?= $this->language->_("Carga")?> ", sortable:true},
	{key:"feching",label:" <?= $this->language->_("Fecha de Ingreso")?> ", sortable:true},
	{key:"descmer",label:" <?= $this->language->_("Descripción Mercadería")?> ", sortable:true},
	{key:"detalle", label:" <?= $this->language->_("Detalle")?> ", sortable:false},
	{key:"mod",label:" <?= $this->language->_("Modificar")?> ", sortable:false},
	{key:"elim",label:" <?= $this->language->_("Eliminar")?> ", sortable:false}];

var hideLabel = "<?= $this->language->_("Oculto")?>";
var showLabel = "<?= $this->language->_("Visible")?>";
var closeLabel = "<?= $this->language->_("Cerrar")?>";
</script>

<script type="text/javascript" src="/js/init_listexportacion.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <? foreach ($this->message as $msg) { ?>
        <div class="msg"><?= $msg ?></div>
    <? } ?>
<? } ?>
<div class="busqueda">
    <?= $this->exportacionSearchForm ?>
</div>
<div id="divdetalles"></div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->language->_("Opciones de la tabla")?></a></div>
<div id="columnshowhide"></div>
<div id="divlistado" class="clistado">
    <table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Órden")?> </th>
            <th> <?= $this->language->_("Transporte")?> </th>
            <th> <?= $this->language->_("Cliente")?> </th>
            <th> <?= $this->language->_("Destino")?> </th>
            <th> <?= $this->language->_("Carga")?> </th>
            <th> <?= $this->language->_("Fecha de Ingreso")?> </th>
            <th> <?= $this->language->_("Descripción Mercadería")?> </th>
            <th> <?= $this->language->_("Detalle")?> </th>
            <th> <?= $this->language->_("Modificar")?> </th>
            <th> <?= $this->language->_("Eliminar")?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $exportacion) { ?>
        <tr>
            <td> <?= $exportacion->orden() ?> </td>
            <td> <?= $exportacion->codTransporteName() ?> </td>
            <td> <?= $exportacion->codClienteName() ?> </td>
            <td> <?= $exportacion->codDestinacionName() ?> </td>
            <td> <?= $exportacion->codCargaName() ?> </td>
            <td> <?= $exportacion->fechaIngreso() ?> </td>
            <td> <?= $exportacion->desMercaderias() ?> </td>
            <td>
            <input type="button" id="botonLindo" onclick="ShowDetails( <?= $exportacion->id() ?> )" value=" <?= $this->language->_("Detalle")?> " />
            </td>
            <td>
                <a href="<?= "/user/exportaciones/modexportaciones/id/" . $exportacion->id() ?>"><?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/exportaciones/removeexportaciones/id/" . $exportacion->id()?>"><?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>

</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>
<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->language->_("Seleccione las columnas que desea ver:")?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>

