<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>
</head>
<body>
    <div class="container">

        <div class="block">
            <div class="column span-6 last">
                <div id="login" class="box">
                    <?= $this->action('adduserstate', 'panel', 'admin') ?>
                </div>
            </div>


        <div class="block">
            <div id="footer" class="span-24">
                <p>Copyright &copy; 2008 Trifiori</p>
            </div>
        </div>
    </div>
</body>
</html>
