<script type="text/javascript">
var myColumnDefs = [{key:"name",label:"Nombre", sortable:false},
	{key:"mod",label:"Modificar", sortable:false},
	{key:"elim",label:"Eliminar", sortable:false}];
</script>
<script type="text/javascript" src="/js/init_listdestinaciones.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->destinacionSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Nombre") ?> </th>
            <th> <?= $this->language->_("Modificar") ?> </th>
            <th> <?= $this->language->_("Eliminar") ?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $destinacion) { ?>
        <tr> 
            <td> <?= $destinacion->name() ?> </td>
            <td>
                <a href="<?= "/user/destinaciones/moddestinaciones/id/" . $destinacion->id() ?>"><img src="/images/modificar.png" alt="<?= $this->language->_("Modificar")?>" title="<?= $this->language->_("Modificar")?>" width="30" height="30"> </a>
            </td>
			<td>
                <a href="<?= "/user/destinaciones/removedestinaciones/id/" . $destinacion->id() ?>"><img src="/images/borrar.png" alt="<?= $this->language->_("Eliminar")?>" title="<?= $this->language->_("Eliminar")?>" width="30" height="30"> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

