<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr> <th>Nombre</th> <th>Modificar</th> <th>Eliminar</th> </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $giro) { ?>
        <tr> 
            <td> <?= $giro["SECCION_GIR"] ?> </td>
            <td>
                <a href="<?= "/user/giros/modgiros/id/" . $giro["CODIGO_GIR"]?>">Modificar</a>
            </td>
			<td>
                <a href="<?= "/user/giros/removegiros/id/" . $giro["CODIGO_GIR"]?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"Nombre", sortable:true},
			{key:"mod",label:"Modificar", sortable:false},
			{key:"elim",label:"Eliminar", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [{key:"name"},
					{key:"mod"},
					{key:"elim"}]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"}}
        );
    };
});
</script>