<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; " />
    <meta name="language" content="es" />
    <title><?php echo $this->escape($this->title) ?></title>
</head>
<body>
    <p><?= $this->escape($this->title) ?></p>
</body>
</html>
