<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>
</head>
<body class="yui-skin-sam">
    <div class="container">
        <div class="block">
            <div class="containerlogin">
                <div id="loginimg" class="cloginimg">
                    <img src="/images/LOGO.JPG" width="200" height="80">
                </div>
                <div id="login" class="cboxlogin">
                    <?= $this->action('loginstate', 'index', 'default') ?>
                </div>
            </div>
        <div class="block">
            <div id="footer" class="cfooter">
                <p>Copyright &copy; 2008 Trifiori</p>
            </div>
        </div>
    </div>
    
</body>
</html>
