<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <link rel="stylesheet" href="/css/login.css" type="text/css" media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css" />
    <script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
    <script type="text/javascript" src="/yui/build/container/container-min.js"></script>
    <?= $this->headTitle() ?>
</head>
<body class="yui-skin-sam">
    <div class="container">
        <div class="block">
            <div class="containerlogin">
                <div id="loginimg" class="cloginimg">
                    <img src="/images/LOGO.JPG" width="200" height="80">
                </div>
                <div id="login" class="cboxlogin">
                    <?= $this->action('loginstate', 'index', 'default') ?>
                </div>
            </div>
        <div class="block">
            <div id="footer" class="cfooter">
                <p>Copyright &copy; 2008 Trifiori</p>
            </div>
        </div>
    </div>
    
<script type="text/javascript">
YAHOO.namespace("login.container");
YAHOO.login.container.tt1 = new YAHOO.widget.Tooltip("tt1", { context:"username", text:"Nombre de usuario (respete mayúsculas y minúsculas)" });
YAHOO.login.container.tt2 = new YAHOO.widget.Tooltip("tt2", { context:"password", text:"Contraseña (respete mayúsculas y minúsculas)" });
</script>
</body>
</html>
