<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>
</head>
<body>
    <div class="container">

        <div class="block">
            <div id="principal" class="column span-24">
                 <table class="bordered">
                    <thead>
                        <tr> <th>Nombre</th> <th>Usuario</th> </tr>
                    </thead>
                    <tbody>
                        <? foreach($this->users as $user) { ?>
                        <tr> <td> <?= $user->NOMBRE_USU ?> </td> <td> <?= $user->USUARIO_USU ?> </td> </tr>
                        <? } ?>
                    </tbody>
                </table>
            </div>

            <div class="column span-6 last">
                <div id="login" class="box">
                    <?= $this->action('loginstate', 'index', 'default') ?>
                </div>
            </div>


        <div class="block">
            <div id="footer" class="span-24">
                <p>Copyright &copy; 2008 Trifiori</p>
            </div>
        </div>
    </div>
</body>
</html>
