<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->escape($this->error) ?></div>
<? } ?>
<? if (isset($this->failedAuthentication)) { ?>
    <div class="error"> <?= $this->escape($this->language->_("Credenciales incorrectas.")) ?> </div>
<? } ?>
<?= $this->loginForm ?>

<div class="cforgotpass">
    <a href="/default/index/forgotpass"> <?= $this->escape($this->language->_("¿Olvidó su contraseña?")) ?> </a>
</div>
