<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <div class="msg"><?= $this->message ?></div>
                        <? } ?>
<div class="cformulario">
	<?= $this->oppAddForm ?>
</div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
    // validacion
    var frmvalidator  = new Validator("form");

    //habilito alert con mensajes
    frmvalidator.EnableOnPageErrorDisplaySingleBox();
    frmvalidator.EnableMsgsTogether();

    frmvalidator.addValidation("pedidoDinero","req","<?= $this->language->_("*Ingrese una fecha de pedido de dinero")?>");
    frmvalidator.addValidation("pedidoDinero","regexp=^(19|20)([0-9]{2})-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])$","<?= $this->language->_("*La fecha del pedido de dinero es inválida")?>");
    
    frmvalidator.addValidation("declaracionOk","req","<?= $this->language->_("*Ingrese un resultado de declaración")?>");
</script>
