<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Número")?> </th>
            <th> <?= $this->language->_("Declaración Ok")?> </th>
            <th> <?= $this->language->_("Pedido de Dinero")?> </th>
            <th> <?= $this->language->_("Otros Opp")?> </th>
            <th> <?= $this->language->_("Fraccionado Opp")?> </th>
            <th> <?= $this->language->_("Estampillas")?> </th>
            <th> <?= $this->language->_("Impuestos Internos")?> </th>
            <th> <?= $this->language->_("Modificar")?> </th>
            <th> <?= $this->language->_("Eliminar")?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $opp) { ?>
        <tr>
            <td> <?= $opp->name()?> </td>
            <td> <?= $opp->declaracionOk()?> </td>
            <td> <?= $opp->pedidoDinero() ?> </td>
            <td> <?= $opp->otrosOpp() ?> </td>
            <td> <?= $opp->fraccionado() ?> </td>
            <td> <?= $opp->estampillas() ?> </td>
            <td> <?= $opp->impuestosInternos() ?> </td>
            <td>
                <a href="<?= "/user/opps/modopps/id/" . $opp->id() ?>"> <?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/opps/removeopps/id/" . $opp->id() ?>"> <?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs =
        [
            {key:"name",label: '<?= $this->language->_("Número")?>', sortable:true},
            {key:"declaracionOk",label:"<?= $this->language->_("Declaración Ok")?>", sortable:true},
            {key:"pedidoDinero",label:"<?= $this->language->_("Pedido de Dinero")?>", sortable:true},
            {key:"otrosOpp",label:"<?= $this->language->_("Otros Opp")?>", sortable:true},
            {key:"fraccionado",label:"<?= $this->language->_("Fraccionado Opp")?>", sortable:true},
            {key:"estampillas",label:"<?= $this->language->_("Estampillas")?>", sortable:true},
            {key:"impuestosInternos",label:"<?= $this->language->_("Impuestos Internos")?>", sortable:true},
            {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
            {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields: [
                        {key:"name"},
                        {key:"declaracionOk"},
                        {key:"pedidoDinero"},
                        {key:"otrosOpp"},
                        {key:"fraccionado"},
                        {key:"estampillas"},
                        {key:"impuestosInternos"},
                        {key:"mod"},
                        {key:"elim"}
                    ]
        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs,
                                                    this.myDataSource,
                                                    {
                                                        sortedBy:{key:"pedidoDinero",dir:"desc"},draggableColumns:true
                                                    }
        );
    };
});
</script>
