<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<div class="cformulario">
    <?= $this->oppModForm ?>
</div>
<div id="calpedidoDinero" style="display:none;" class="ccalfechaingreso"></div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
    YAHOO.namespace("local.calendar");

    YAHOO.local.calendar.init = function()
    {
        var eLog = YAHOO.util.Dom.get("evtentries");

        YAHOO.local.calendar.fechaDinero = new YAHOO.widget.Calendar("calpedidoDinero");
        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.fechaDinero.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.fechaDinero.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.fechaDinero.selectEvent.subscribe(handlerCalFechaDineroES,
                YAHOO.local.calendar.fechaDinero, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.fechaDinero.selectEvent.subscribe(handlerCalFechaDineroEN,
                YAHOO.local.calendar.fechaDinero, true);
        <? } ?>

        YAHOO.local.calendar.fechaDinero.render();
    }

    YAHOO.util.Event.onDOMReady(YAHOO.local.calendar.init);

    // validacion
    var frmvalidator  = new Validator("form");

    //habilito alert con mensajes
    frmvalidator.EnableOnPageErrorDisplaySingleBox();
    frmvalidator.EnableMsgsTogether();

    frmvalidator.addValidation("pedidoDinero","req","<?= $this->language->_("*Ingrese una fecha de pedido de dinero")?>");
    frmvalidator.addValidation("pedidoDinero","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha del pedido de dinero es inválida")?>");
    
    frmvalidator.addValidation("declaracionOk","req","<?= $this->language->_("*Ingrese un resultado de declaración")?>");
</script>
