<? if (isset($this->error)) { ?>
    <div class="error_fatal"><?= $this->escape($this->error) ?></div>
    <div id="errmsg"></div>
    <script languaje="javascript">
        var time=0;
        showAlert("errmsg", { width:"620px", modal:true, visible:true, underlay:"shadow", fixedcenter:true, constraintoviewport:true, draggable:false } , "Error Fatal", "<div id='diverror' class='error_fatal'><?= $this->escape($this->language->_($this->error)) ?></div><br><div id='idtimeerror'></div>", "Trifiori");
        setInterval (function (){if (time==5){document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando al Home...'))?>";window.location.href = "/";}else{ document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando en'))?> " + (5-time); time++;}}, 1000);
    </script>
<? } else { ?>
            <? if (isset($this->message)) { ?>
                <div class="msg"><?= $this->escape($this->message) ?></div>
                        <? } ?>
<div class="cformulario">
	<?= $this->proveedorAddForm ?>
</div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
    // validacion
    var frmvalidator  = new Validator("form");

    //habilito alert con mensajes
    frmvalidator.EnableOnPageErrorDisplaySingleBox();
    frmvalidator.EnableMsgsTogether();

    frmvalidator.addValidation("name","req","<?= $this->language->_("*Ingrese un nombre")?>");
    frmvalidator.addValidation("name","alnum_s ","<?= $this->language->_("*El nombre debe ser alfanumérico")?>");
    frmvalidator.addValidation("name","maxlen=20","<?= $this->language->_("*El nombre debe contener hasta 20 caracteres")?>");

    frmvalidator.addValidation("adress","req","<?= $this->language->_("*Ingrese una dirección")?>");
    frmvalidator.addValidation("adress","alnum_s ","<?= $this->language->_("*La dirección debe ser alfanumérica")?>");
    frmvalidator.addValidation("adress","maxlen=100","<?= $this->language->_("*La dirección debe contener hasta 100 caracteres")?>");

    frmvalidator.addValidation("tel","req","<?= $this->language->_("*Ingrese un teléfono")?>");
    frmvalidator.addValidation("tel","alnum_s ","<?= $this->language->_("*El teléfono debe ser alfanumérico")?>");

</script>
<? } ?>
