<!-- queda en el php las cosas a traducir -->
<script type="text/javascript">
var myColumnDefs = [
	{key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:false},
	{key:"adress",label:"<?= $this->language->_("Dirección")?>", sortable:false},
	{key:"tel",label:"<?= $this->language->_("Teléfono")?>", sortable:false},
	{key:"fax",label:"<?= $this->language->_("Fax")?>", sortable:false},
	{key:"mail",label:"<?= $this->language->_("E-mail")?>", sortable:false},
	{key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
	{key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}];

var hideLabel = "<?= $this->language->_("Oculto")?>";
var showLabel = "<?= $this->language->_("Visible")?>";
var closeLabel = "<?= $this->language->_("Cerrar")?>";
</script>
<script type="text/javascript" src="/js/init_listproveedores.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->proveedorSearchForm ?>
</div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->language->_("Opciones de la tabla")?></a></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Nombre")?></th>
        <th><?= $this->language->_("Dirección")?></th>
        <th><?= $this->language->_("Teléfono")?></th>
        <th><?= $this->language->_("Fax")?></th>
        <th><?= $this->language->_("E-mail")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $proveedor) { ?>
        <tr> 
            <td> <?= $proveedor->name() ?> </td>
            <td> <?= $proveedor->adress() ?> </td>
            <td> <?= $proveedor->tel() ?> </td>
            <td> <?= $proveedor->fax() ?> </td>
            <td> <?= $proveedor->mail() ?> </td>
            <td>
                <a href="<?= "/user/proveedores/modproveedores/id/" . $proveedor->id() ?>"><img src="/images/modificar.png" alt="<?= $this->language->_("Modificar")?>" title="<?= $this->language->_("Modificar")?>" width="30" height="30"></a>
            </td>
            <td>
                <a href="<?= "/user/proveedores/removeproveedores/id/" . $proveedor->id() ?>"><img src="/images/borrar.png" alt="<?= $this->language->_("Eliminar")?>" title="<?= $this->language->_("Eliminar")?>" width="30" height="30"></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->language->_("Seleccione las columnas que desea ver:")?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>

