<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->proveedorSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Nombre")?></th>
        <th><?= $this->language->_("Dirección")?></th>
        <th><?= $this->language->_("Teléfono")?></th>
        <th><?= $this->language->_("Fax")?></th>
        <th><?= $this->language->_("E-mail")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $proveedor) { ?>
        <tr> 
            <td> <?= $proveedor->name() ?> </td>
            <td> <?= $proveedor->adress() ?> </td>
            <td> <?= $proveedor->tel() ?> </td>
            <td> <?= $proveedor->fax() ?> </td>
            <td> <?= $proveedor->mail() ?> </td>
            <td>
                <a href="<?= "/user/proveedores/modproveedores/id/" . $proveedor->id() ?>">Modificar</a>
            </td>
            <td>
                <a href="<?= "/user/proveedores/removeproveedores/id/" . $proveedor->id() ?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
            {key:"adress",label:"<?= $this->language->_("Dirección")?>", sortable:true},
        {key:"tel",label:"<?= $this->language->_("Teléfono")?>", sortable:true},
        {key:"fax",label:"<?= $this->language->_("Fax")?>", sortable:true},
        {key:"mail",label:"<?= $this->language->_("E-mail")?>", sortable:true},
        {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
        {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [
                    {key:"name"},
                    {key:"adress"},
                    {key:"tel"},
                    {key:"fax"},
                    {key:"mail"},
                    {key:"mod"},
                    {key:"elim"}
                    ]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true}
        );
    };
});
</script>
