<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->escape($this->error) ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <div class="msg"><?= $this->escape($this->message) ?></div>
                        <? } ?>
<div class="cformulario">
	<?= $this->puertoAddForm ?>
</div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
    // validacion
    var frmvalidator  = new Validator("form");
    
    //habilito alert con mensajes
    frmvalidator.EnableOnPageErrorDisplaySingleBox();
    frmvalidator.EnableMsgsTogether();
    
    frmvalidator.addValidation("name","req","<?= $this->language->_("*Ingrese un nombre")?>");
    frmvalidator.addValidation("name","alnum_s ","<?= $this->language->_("*El nombre debe ser alfanumérico")?>");
    frmvalidator.addValidation("name","maxlen=20","<?= $this->language->_("*El nombre debe contener hasta 20 caracteres")?>");

    frmvalidator.addValidation("latitud","dec ","<?= $this->language->_("*La latitud debe ser decimal")?>");
    frmvalidator.addValidation("latitud","maxlen=15","<?= $this->language->_("*La latitud puede contener hasta 15 valores")?>");

    frmvalidator.addValidation("longitud","dec ","<?= $this->language->_("*La longitud debe ser decimal")?>");
    frmvalidator.addValidation("longitud","maxlen=15","<?= $this->language->_("*La longitud puede contener hasta 15 valores")?>");

</script>
