<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->puertoSearchForm ?>
</div>
<div id="divmap"></div>
<div id="test"></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Nombre")?></th>
        <th><?= $this->language->_("Ubicación")?></th>
        <th><?= $this->language->_("Mapa")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $puerto) { ?>
        <tr> 
            <td> <?= $puerto->name() ?> </td>
            <td> <?= $puerto->ubicacion() ?> </td>
	    <td> <a href="#" onclick="showMap(<?= $puerto->latitud() ?>,<?= $puerto->longitud() ?>);">Ver Mapa</a> </td>
            <td>
                <a href="<?= "/user/puertos/modpuertos/id/" . $puerto->id() ?>">Modificar</a>
            </td>
            <td>
                <a href="<?= "/user/puertos/removepuertos/id/" . $puerto->id() ?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
            {key:"ubicacion",label:"<?= $this->language->_("Ubicación")?>", sortable:true},
	{key:"mapa",label:"<?= $this->language->_("Mapa")?>", sortable:true},
        {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
        {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [
                    {key:"name"},
                    {key:"ubicacion"},
		    {key:"mapa"},
                    {key:"mod"},
                    {key:"elim"}
                    ]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true}
        );
    };
});
</script>
