<table class="bordered">
    <thead>
        <tr> <th>ID</th> <th>Nombre</th> </tr>
    </thead>
    <tbody>
        <? foreach($this->Puertos as $puerto) { ?>
        <tr> <td> <?= $puerto->id() ?> </td>
            <td> <?= $puerto->name() ?> </td>
            <td>
                <a href="<?= $this->baseUrl . "removepuertos/id/" . $puerto->id()?>">Eliminar</a>
            </td>
            <td>
                <a href="<?= $this->baseUrl . "modpuertos/id/" . $puerto->id()?>">Modificar</a>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>