<!-- queda en el php las cosas a traducir -->
<script type="text/javascript">
var myColumnDefs = [
	{key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
	{key:"ubicacion",label:"<?= $this->language->_("Ubicación")?>", sortable:true},
	{key:"mapa",label:"<?= $this->language->_("Mapa")?>", sortable:true},
	{key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
	{key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}];

var hideLabel = "<?= $this->language->_("Oculto")?>";
var showLabel = "<?= $this->language->_("Visible")?>";
var closeLabel = "<?= $this->language->_("Cerrar")?>";
</script>
<script type="text/javascript" src="/js/init_listpuertos.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->puertoSearchForm ?>
</div>
<div id="divmap"></div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->language->_("Opciones de la tabla")?></a></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Nombre")?></th>
        <th><?= $this->language->_("Ubicación")?></th>
        <th><?= $this->language->_("Mapa")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $puerto) { ?>
        <tr> 
            <td> <?= $puerto->name() ?> </td>
            <td> <?= $puerto->ubicacion() ?> </td>
	    <td> <a href="#" onclick="showMap(<?= $puerto->latitud() ?>,<?= $puerto->longitud() ?>);"><img src="/images/map.gif" alt="<?= $this->language->_("Ver Mapa")?>" title="<?= $this->language->_("Ver Mapa")?>" width="30" height="30"></a> </td>
            <td align="center">
                <a href="<?= "/user/puertos/modpuertos/id/" . $puerto->id() ?>"><img src="/images/modificar.png" alt="<?= $this->language->_("Modificar")?>" title="<?= $this->language->_("Modificar")?>" width="30" height="30"> </a>
            </td>
            <td align="center">
                <a href="<?= "/user/puertos/removepuertos/id/" . $puerto->id() ?>"><img src="/images/borrar.png" alt="<?= $this->language->_("Eliminar")?>" title="<?= $this->language->_("Eliminar")?>" width="30" height="30"></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->language->_("Seleccione las columnas que desea ver:")?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>

