<!-- queda en el php las cosas a traducir -->
<script type="text/javascript">
var myColumnDefs = [
    {key:"name",label:"<?= $this->language->_("Nombre")?> ", sortable:true},
    {key:"mod",label:"<?= $this->language->_("Modificar")?> ", sortable:false},
    {key:"elim",label:"<?= $this->language->_("Eliminar")?> ", sortable:false}];
</script>
<script type="text/javascript" src="/js/init_listbanderas.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <? foreach ($this->message as $msg) { ?>
        <div class="msg"><?= $msg ?></div>
    <? } ?>
<? } ?>
<div class="busqueda">
    <?= $this->banderaSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Nombre") ?> </th>
            <th> <?= $this->language->_("Modificar") ?> </th>
            <th> <?= $this->language->_("Eliminar") ?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $bandera) { ?>
        <tr>
            <td> <?= $bandera->name() ?> </td>
            <td>
                <a href="<?= "/user/banderas/modbanderas/id/" . $bandera->id()?>"><?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/banderas/removebanderas/id/" . $bandera->id()?>"><?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

