<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Nombre") ?> </th>
            <th> <?= $this->language->_("Modificar") ?> </th>
            <th> <?= $this->language->_("Eliminar") ?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $bandera) { ?>
        <tr>
            <td> <?= $bandera->name() ?> </td>
            <td>
                <a href="<?= "/user/banderas/modbanderas/id/" . $bandera->id()?>"><?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/banderas/removebanderas/id/" . $bandera->id()?>"><?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"<?= $this->language->_("Nombre")?> ", sortable:true},
            {key:"mod",label:"<?= $this->language->_("Modificar")?> ", sortable:false},
            {key:"elim",label:"<?= $this->language->_("Eliminar")?> ", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields:
                [
                    {key:"name"},
                    {key:"mod"},
                    {key:"elim"}
                ]
            };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"}}
        );
    };
});
</script>
