<table class="bordered">
    <thead>
        <tr> <th>ID</th> <th>Nombre</th> </tr>
    </thead>
    <tbody>
        <? foreach($this->Banderas as $bandera) { ?>
        <tr> <td> <?= $bandera->id() ?> </td>
            <td> <?= $bandera->name() ?> </td>
            <td>
                <a href="<?= $this->baseUrl . "removebanderas/id/" . $bandera->id()?>">Eliminar</a>
            </td>
            <td>
                <a href="<?= $this->baseUrl . "modbanderas/id/" . $bandera->id()?>">Modificar</a>
            </td>
        </tr>
        <? } ?>
    </tbody>
</table>