<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<div class="busqueda">
    <?= $this->logSearchForm ?>
</div>      
<div id="divmodificaciones" class="clistado">
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $log) { ?>
            <?= $this->escape($this->language->_("ID")) . ": " . $this->escape($log->id()) ?> <br />
            <td> <?= $this->escape($this->language->_("Nivel")) . ": " . $this->escape($log->nivel()) ?> <br />
            <td> <?= $this->escape($this->language->_("Mensaje")) . ": " . $this->escape($log->msg()) ?> <br /><br />
        <? } ?>
    <? } ?>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<a href="<?= "/mobile/admin/index" ?>"> <?= $this->escape($this->language->_("Menu Principal")) ?> </a><br />
<a href="<?= "/mobile/index/logout" ?>"> <?= $this->escape($this->language->_("Logout"))?> </a>
