<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Nombre")?> </th>
            <th> <?= $this->language->_("Dirección")?> </th>
            <th> <?= $this->language->_("Código Postal")?> </th>
            <th> <?= $this->language->_("Localidad")?> </th>
            <th> <?= $this->language->_("CUIT")?> </th>
            <th> <?= $this->language->_("Tipo IVA")?> </th>
            <th> <?= $this->language->_("Tipo Cliente")?> </th>
            <th> <?= $this->language->_("Modificar")?> </th>
            <th> <?= $this->language->_("Eliminar")?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $cliente) { ?>
        <tr>
            <td> <?= $cliente->name()?> </td>
            <td> <?= $cliente->adress() ?> </td>
            <td> <?= $cliente->codPostal() ?> </td>
            <td> <?= $cliente->localidad() ?> </td>
            <td> <?= $cliente->CUIT() ?> </td>
            <td> <?= $cliente->tipoIVA() ?> </td>
            <td> <?= $cliente->tipoCliente() ?> </td>
            <td>
                <a href="<?= "/user/clientes/modclientes/id/" . $cliente->id() ?>"> <?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/clientes/removeclientes/id/" . $cliente->id() ?>"> <?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>

<div id="myContainer"></div>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs =
        [
            {key:"name",label: '<?= $this->language->_("Nombre")?>', sortable:true},
            {key:"address",label: '<?= $this->language->_("Dirección")?>', sortable:true},
            {key:"cp",label: '<?= $this->language->_("Código Postal")?>', sortable:true},
            {key:"local",label: '<?= $this->language->_("Localidad")?>', sortable:true},
            {key:"cuit",label: '<?= $this->language->_("CUIT")?>', sortable:true},
            {key:"iva",label: '<?= $this->language->_("Tipo Iva")?>', sortable:true},
            {key:"type",label: '<?= $this->language->_("Tipo Cliente")?>', sortable:true},
            {key:"mod",label: '<?= $this->language->_("Modificar")?>', sortable:false},
            {key:"elim",label: '<?= $this->language->_("Eliminar")?>', sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields:
                [
                    {key:"name"},
                    {key:"address"},
                    {key:"cp"},
                    {key:"local"},
                    {key:"cuit"},
                    {key:"iva"},
                    {key:"type"},
                    {key:"mod"},
                    {key:"elim"}
                ]
        };

        var myDT = this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true});
    };
});
</script>
