<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Código Postal</th>
            <th>Localidad</th>
            <th>CUIT</th>
            <th>Tipo IVA</th>
            <th>Tipo Cliente</th>
			<th>Modificar</th> <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $cliente) { ?>
        <tr>
            <td> <?= $cliente["NOMBRE_CLI"] ?> </td>
            <td> <?= $cliente["DIRECCION_CLI"] ?> </td>
            <td> <?= $cliente["CODIGOPOSTAL_CLI"] ?> </td>
            <td> <?= $cliente["LOCALIDAD_CLI"] ?> </td>
            <td> <?= $cliente["CUIT_CLI"] ?> </td>
            <td> <?= $cliente["TIPOIVA_CLI"] ?> </td>
            <td> <?= $cliente["TIPOCLIENTE_CLI"] ?> </td>
            <td>
                <a href="<?= "/user/clientes/modclientes/id/" . $cliente["CODIGO_CLI"]?>">Modificar</a>
            </td>
            <td>
                <a href="<?= "/user/clientes/removeclientes/id/" . $cliente["CODIGO_CLI"]?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"Nombre", sortable:true},
			{key:"address",label:"Direccion", sortable:true},
			{key:"cp",label:"Codigo Postal", sortable:true},
			{key:"local",label:"Localidad", sortable:true},
			{key:"cuit",label:"CUIT", sortable:true},
			{key:"iva",label:"Tipo Iva", sortable:true},
			{key:"type",label:"Tipo Cliente", sortable:true},
			{key:"mod",label:"Modificar", sortable:false},
			{key:"elim",label:"Eliminar", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [{key:"name"},
					{key:"address"},
					{key:"cp"},
					{key:"local"},
					{key:"cuit"},
					{key:"iva"},
					{key:"type"},
					{key:"mod"},
					{key:"elim"}]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"}}
        );
    };
});
</script>