<!-- 
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<? $this->language = Zend_Registry::getInstance()->language; ?>
<? $this->busqueda = Zend_Registry::getInstance()->busqueda; ?>
<? $this->sortby = Zend_Registry::getInstance()->sortby; ?>
<? $this->sorttype = Zend_Registry::getInstance()->sorttype; ?>

<?php if ($this->pageCount): ?> 
<div class="paginationControl">
<!-- Previous page link --> 
<?php if (isset($this->previous)): ?> 
        <a href="<?= $this->escape($this->url()) . "?consulta=" . $this->escape($this->busqueda) . "&page=" . $this->escape($this->previous)
            . "&sortby=" . $this->escape($this->sortby) . "&sort=" . $this->escape($this->sorttype); ?>">
            &lt; <?= $this->escape($this->language->_("Anterior")) ?> </a> |
<?php else: ?> 
  <span class="disabled">&lt; <?= $this->escape($this->language->_("Anterior")) ?> </span> |
<?php endif; ?> 

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?> 
  <?php if ($page != $this->current): ?>
    <a href="<?= $this->escape($this->url()) . "?consulta=" . $this->escape($this->busqueda) . "&page=" . $this->escape($page)
            . "&sortby=" . $this->escape($this->sortby) . "&sort=" . $this->escape($this->sorttype); ?>">
            <?= $this->escape($page); ?></a>
  <?php else: ?>
    <?= $this->escape($page); ?> | 
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link --> 
<?php if (isset($this->next)): ?> 
        <a href="<?= $this->escape($this->url()) . "?consulta=" . $this->escape($this->busqueda) . "&page=" . $this->escape($this->next)
                . "&sortby=" . $this->escape($this->sortby) . "&sort=" . $this->escape($this->sorttype); ?>"> 
                <?= $this->escape($this->language->_("Próximo")) ?>  &gt;</a>
<?php else: ?> 
  <span class="disabled"> <?= $this->escape($this->language->_("Próximo")) ?>  &gt;</span>
<?php endif; ?> 
</div> 
<?php endif; ?>
