<? if (isset($this->error)) { ?>
    <div class="error_fatal"><?= $this->escape($this->error) ?></div>
    <div id="errmsg"></div>
    <script languaje="javascript">
        var time=0;
        showAlert("errmsg", { width:"620px", modal:true, visible:true, underlay:"shadow", fixedcenter:true, constraintoviewport:true, draggable:false } , "Error Fatal", "<div id='diverror' class='error_fatal'><?= $this->escape($this->language->_($this->error)) ?></div><br><div id='idtimeerror'></div>", "Trifiori");
        setInterval (function (){if (time==5){document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando al Home...'))?>";window.location.href = "/";}else{ document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando en'))?> " + (5-time); time++;}}, 1000);
    </script>
<? } else { ?>
<script type="text/javascript">
var myColumnDefs =
[
    {key:"orden",label:"<?= $this->escape($this->language->_("Orden"))?>", sortable:false},
    {key:"codCanalName",label:"<?= $this->escape($this->language->_("Canal"))?>", sortable:false},
    {key:"codClienteName",label:"<?= $this->escape($this->language->_("Cliente"))?>", sortable:false},
    {key:"codOppName",label:"<?= $this->escape($this->language->_("Opp"))?>", sortable:false},
    {key:"desMercaderias",label:"<?= $this->escape($this->language->_("Descripción Mercadería"))?>", sortable:false},
    {key:"valorFactura",label:"<?= $this->escape($this->language->_("Valor Factura"))?>", sortable:false},
    {key:"ingresoPuerto",label:"<?= $this->escape($this->language->_("Ingreso a Puerto"))?>", sortable:false},
    {key:"detalle", label:" <?= $this->escape($this->language->_("Detalle"))?> ", sortable:false},
    {key:"reporte",label:"<?= $this->escape($this->language->_("Reporte"))?>", sortable:false},
    {key:"mod",label:"<?= $this->escape($this->language->_("Modificar"))?>", sortable:false},
    {key:"elim",label:"<?= $this->escape($this->language->_("Eliminar"))?>", sortable:false}
];

var hideLabel = "<?= $this->escape($this->language->_("Oculto"))?>";
var showLabel = "<?= $this->escape($this->language->_("Visible"))?>";
var closeLabel = "<?= $this->escape($this->language->_("Cerrar"))?>";
</script>
<script type="text/javascript" src="/js/init_listimportacion.js"></script>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $this->escape($msg) ?></div>
                            <? } ?>
                            <? } ?>

<div class="busqueda">
    <?= $this->importacionSearchForm ?>
</div>
<div id="divdetalles"></div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->escape($this->language->_("Opciones de la tabla"))?></a></div>
<div id="divlistado" class="clistado">
    <table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->escape($this->language->_("Órden"))?></th>
        <th><?= $this->escape($this->language->_("Canal"))?></th>
        <th><?= $this->escape($this->language->_("Cliente"))?></th>
        <th><?= $this->escape($this->language->_("Opp"))?></th>
        <th><?= $this->escape($this->language->_("Descripción Mercadería"))?></th>
        <th><?= $this->escape($this->language->_("Valor Factura"))?></th>
        <th><?= $this->escape($this->language->_("Ingreso a Puerto"))?></th>
        <th><?= $this->escape($this->language->_("Detalle"))?> </th>
        <th><?= $this->escape($this->language->_("Reporte"))?></th>
        <th><?= $this->escape($this->language->_("Modificar"))?></th>
        <th><?= $this->escape($this->language->_("Eliminar"))?></th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $importacion) { ?>
        <tr>
            <td> <?= $this->escape($importacion->orden()) ?> </td>
            <td> <?= $this->escape($importacion->codCanalName()) ?> </td>
            <td> <?= $this->escape($importacion->codClienteName()) ?> </td>
            <td> <?= $this->escape($importacion->codOppNum()) ?> </td>
            <td> <?= $this->escape($importacion->desMercaderias()) ?> </td>
            <td> <?= $this->escape($importacion->valorFactura()) ?> </td>
            <td> <?= $this->escape($importacion->ingresoPuerto()) ?> </td>
            <td>
            <input type="button" id="botonLindo" onclick="ShowDetailsImp( <?= $importacion->id() ?> )" value=" <?= $this->escape($this->language->_("Detalle"))?> " />
            </td>
            <td>
                <a href="<?= "/user/importaciones/pdf/id/" . $this->escape($importacion->id()) ?>"><img src="/images/pdf.png" alt="<?= $this->escape($this->language->_("Reporte"))?>" title="<?= $this->escape($this->language->_("Reporte"))?>" width="30" height="30"></a>
            </td>
            <td>
                <a href="<?= "/user/importaciones/modimportaciones/id/" . $this->escape($importacion->id()) ?>"><img src="/images/modificar.png" alt="<?= $this->escape($this->language->_("Modificar"))?>" title="<?= $this->escape($this->language->_("Modificar"))?>" width="30" height="30"></a>
            </td>
            <td>
                <a href="<?= "/user/importaciones/removeimportaciones/id/" . $this->escape($importacion->id())?>"><img src="/images/borrar.png" alt="<?= $this->escape($this->language->_("Eliminar"))?>" title="<?= $this->escape($this->language->_("Eliminar"))?>" width="30" height="30"></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>

</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->escape($this->language->_("Seleccione las columnas que desea ver:"))?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>
<? } ?>
