<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <? foreach ($this->message as $msg) { ?>
        <div class="msg"><?= $msg ?></div>
    <? } ?>
<? } ?>
<div class="busqueda">
    <?= $this->importacionSearchForm ?>
</div>
<div id="divlistado" class="clistado">
    <table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Órden")?></th>
        <th><?= $this->language->_("Destino")?></th>
        <th><?= $this->language->_("Canal")?></th>
        <th><?= $this->language->_("Cliente")?></th>
        <th><?= $this->language->_("Carga")?></th>
        <th><?= $this->language->_("Opp")?></th>
        <th><?= $this->language->_("Fecha de Ingreso")?></th>
        <th><?= $this->language->_("Descripción Mercadería")?></th>
        <th><?= $this->language->_("D: Nro Documento")?></th>
        <th><?= $this->language->_("D: Vencimiento")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $importacion) { ?>
        <tr>
            <td> <?= $importacion->orden() ?> </td>
            <td> <?= $importacion->codDestinacionName() ?> </td>
            <td> <?= $importacion->codCanalName() ?> </td>
            <td> <?= $importacion->codClienteName() ?> </td>
            <td> <?= $importacion->codCargaName() ?> </td>
            <td> <?= $importacion->codOppNum() ?> </td>
            <td> <?= $importacion->fechaIngreso() ?> </td>
            <td> <?= $importacion->desMercaderias() ?> </td>
            <td> <?= $importacion->DESnroDoc() ?> </td>
            <td> <?= $importacion->DESvencimiento() ?> </td>
            <td>
                <a href="<?= "/user/importaciones/modimportaciones/id/" . $importacion->id() ?>"><?= $this->language->_("Modificar")?></a>
            </td>
            <td>
                <a href="<?= "/user/importaciones/removeimportaciones/id/" . $importacion->id()?>"><?= $this->language->_("Eliminar")?></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>

</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"orden",label:"<?= $this->language->_("Orden")?>", sortable:true},
        {key:"codDestinacionName",label:"<?= $this->language->_("Destino")?>", sortable:true},
        {key:"codCanalName",label:"<?= $this->language->_("Canal")?>", sortable:true},
        {key:"codClienteName",label:"<?= $this->language->_("Cliente")?>", sortable:true},
        {key:"codCargaName",label:"<?= $this->language->_("Carga")?>", sortable:true},
        {key:"codOppName",label:"<?= $this->language->_("Opp")?>", sortable:true},
        {key:"fechaIngreso", label:"<?= $this->language->_("Fecha de Ingreso")?>", sortable:true},
        {key:"desMercaderias",label:"<?= $this->language->_("Descripción Mercadería")?>", sortable:true},
        {key:"DESnroDoc",label:"<?= $this->language->_("D: Nro Documento")?>", sortable:true},
        {key:"DESvencimiento",label:"<?= $this->language->_("D: Vencimiento")?>", sortable:true},
        {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
        {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields:
            [
                {key:"orden"},
                {key:"codDestinacionName"},
                {key:"codCanalName"},
                {key:"codClienteName"},
                {key:"codCargaName"},
                {key:"codOppName"},
                {key:"fechaIngreso"},
                {key:"desMercaderias"},
                {key:"DESnroDoc"},
                {key:"DESvencimiento"},
                {key:"mod"},
                {key:"elim"}
            ]
        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"orden",dir:"desc"}}
        );
    };
});
</script>
