<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div id="divlistado" class="clistado">
    <table id="tablelist">
    <thead>
        <tr>
        <th><?= $this->language->_("Órden")?></th>
        <th><?= $this->language->_("Destino")?></th>
        <th><?= $this->language->_("Bandera")?></th>
        <th><?= $this->language->_("Canal")?></th>
        <th><?= $this->language->_("Giro")?></th>
        <th><?= $this->language->_("Cliente")?></th>
        <th><?= $this->language->_("Carga")?></th>
        <th><?= $this->language->_("Transporte")?></th>
        <th><?= $this->language->_("Moneda")?></th>
        <th><?= $this->language->_("Opp")?></th>
        <th><?= $this->language->_("Referencia")?></th>
        <th><?= $this->language->_("Fecha de Ingreso")?></th>
        <th><?= $this->language->_("Original/Copia")?></th>
        <th><?= $this->language->_("Descripción Mercadería")?></th>
        <th><?= $this->language->_("Valor Factura")?></th>
        <th><?= $this->language->_("Documentación Transporte")?></th>
        <th><?= $this->language->_("Ingreso a Puerto")?></th>
        <th><?= $this->language->_("Despacho: Nro Documento")?></th>
        <th><?= $this->language->_("Despacho: Vencimiento")?></th>
        <th><?= $this->language->_("Despacho: B/L")?></th>
        <th><?= $this->language->_("Despacho: Declaración")?></th>
        <th><?= $this->language->_("Despacho: Presentado")?></th>
        <th><?= $this->language->_("Despacho: Salido")?></th>
        <th><?= $this->language->_("Despacho: Cargado")?></th>
        <th><?= $this->language->_("Despacho: Factura")?></th>
        <th><?= $this->language->_("Despacho: Fecha de la Factura")?></th>
        <th><?= $this->language->_("Modificar")?></th>
        <th><?= $this->language->_("Eliminar")?></th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $importacion) { ?>
        <tr>
            <td> <?= $importacion->orden() ?> </td>
            <td> <?= $importacion->codDestinacionName() ?> </td>
            <td> <?= $importacion->codBanderaName() ?> </td>
            <td> <?= $importacion->codCanalName() ?> </td>
            <td> <?= $importacion->codGiroName() ?> </td>
            <td> <?= $importacion->codClienteName() ?> </td>
            <td> <?= $importacion->codCargaName() ?> </td>
            <td> <?= $importacion->codTransporteName() ?> </td>
            <td> <?= $importacion->codMonedaName() ?> </td>
            <td> <?= $importacion->codOppName() ?> </td>
            <td> <?= $importacion->referencia() ?> </td>
            <td> <?= $importacion->fechaIngreso() ?> </td>
            <td> <?= $importacion->originalCopia() ?> </td>
            <td> <?= $importacion->desMercaderias() ?> </td>
            <td> <?= $importacion->valorFactura() ?> </td>
            <td> <?= $importacion->docTransporte() ?> </td>
            <td> <?= $importacion->ingresoPuerto() ?> </td>
            <td> <?= $importacion->DESnroDoc() ?> </td>
            <td> <?= $importacion->DESvencimiento() ?> </td>
            <td> <?= $importacion->DESbl() ?> </td>
            <td> <?= $importacion->DESdeclaracion() ?> </td>
            <td> <?= $importacion->DESpresentado() ?> </td>
            <td> <?= $importacion->DESsalido() ?> </td>
            <td> <?= $importacion->DEScargado() ?> </td>
            <td> <?= $importacion->DESfactura() ?> </td>
            <td> <?= $importacion->DEsfechaFactura() ?> </td>
            <td>
                <a href="<?= "/user/importaciones/modimportaciones/id/" . $importacion->id() ?>"><?= $this->language->_("Modificar")?></a>
            </td>
            <td>
                <a href="<?= "/user/importaciones/removeimportaciones/id/" . $importacion->id()?>"><?= $this->language->_("Eliminar")?></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>

</table>
</div>

<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"orden",label:"<?= $this->language->_("Orden")?>", sortable:true},
        {key:"codDestinacionName",label:"<?= $this->language->_("Destino")?>", sortable:true},
        {key:"codBanderaName",label:"<?= $this->language->_("Bandera")?>", sortable:true},
        {key:"codCanalName",label:"<?= $this->language->_("Canal")?>", sortable:true},
        {key:"codGiroName",label:"<?= $this->language->_("Giro")?>", sortable:true},
        {key:"codClienteName",label:"<?= $this->language->_("Cliente")?>", sortable:true},
        {key:"codCargaName",label:"<?= $this->language->_("Carga")?>", sortable:true},
        {key:"codTransporteName",label:"<?= $this->language->_("Transporte")?>", sortable:true},
        {key:"codMonedaName",label:"<?= $this->language->_("Moneda")?>", sortable:true},
        {key:"codOppName",label:"<?= $this->language->_("Opp")?>", sortable:true},
        {key:"referencia",label:"<?= $this->language->_("Referencia")?>", sortable:true},
        {key:"fechaIngreso", label:"<?= $this->language->_("Fecha de Ingreso")?>", sortable:true},
        {key:"originalCopia",label:"<?= $this->language->_("Original/Copia")?>", sortable:true},
        {key:"desMercaderias",label:"<?= $this->language->_("Descripción Mercadería")?>", sortable:true},
        {key:"valorFactura",label:"<?= $this->language->_("Valor Factura")?>", sortable:true},
        {key:"docTransporte",label:"<?= $this->language->_("Documentación Transporte")?>", sortable:true},
        {key:"ingresoPuerto",label:"<?= $this->language->_("Ingreso a Puerto")?>", sortable:true},
        {key:"DESnroDoc",label:"<?= $this->language->_("Despacho: Nro Documento")?>", sortable:true},
        {key:"DESvencimiento",label:"<?= $this->language->_("Despacho: Vencimiento")?>", sortable:true},
        {key:"DESbl",label:"<?= $this->language->_("Despacho: B/L")?>", sortable:true},
        {key:"DESdeclaracion",label:"<?= $this->language->_("Despacho: Declaración")?>", sortable:true},
        {key:"DESpresentado",label:"<?= $this->language->_("Despacho: Presentado")?>?", sortable:true},
        {key:"DESsalido",label:"<?= $this->language->_("Despacho: Salido")?>", sortable:true},
        {key:"DEScargado",label:"<?= $this->language->_("Despacho: Cargado")?>", sortable:true},
        {key:"DESfactura",label:"<?= $this->language->_("Despacho: Factura")?>", sortable:true},
        {key:"DEsfechaFactura",label:"<?= $this->language->_("Despacho: Fecha de la Factura")?>", sortable:true},
        {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
        {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields:
            [
                {key:"orden"},
                {key:"codDestinacionName"},
                {key:"codBanderaName"},
                {key:"codCanalName"},
                {key:"codGiroName"},
                {key:"codClienteName"},
                {key:"codCargaName"},
                {key:"codTransporteName"},
                {key:"codMonedaName"},
                {key:"codOppName"},
                {key:"referencia"},
                {key:"fechaIngreso"},
                {key:"originalCopia"},
                {key:"desMercaderias"},
                {key:"valorFactura"},
                {key:"docTransporte"},
                {key:"ingresoPuerto"},
                {key:"DESnroDoc"},
                {key:"DESvencimiento"},
                {key:"DESbl"},
                {key:"DESdeclaracion"},
                {key:"DESpresentado"},
                {key:"DESsalido"},
                {key:"DEScargado"},
                {key:"DESfactura"},
                {key:"DEsfechaFactura"},
                {key:"mod"},
                {key:"elim"}
            ]
        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"orden",dir:"desc"}}
        );
    };
});
</script>
