<script type="text/javascript">
    YAHOO.namespace("local.calendar");

    YAHOO.local.calendar.init = function()
    {
        var eLog = YAHOO.util.Dom.get("evtentries");
        YAHOO.local.calendar.fechaIngreso = new YAHOO.widget.Calendar("idFechaIngreso","calFechaIngreso");
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.fechaIngreso.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.fechaIngreso.selectEvent.subscribe(handlerCalFechaIngresoES,
                YAHOO.local.calendar.fechaIngreso, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.fechaIngreso.selectEvent.subscribe(handlerCalFechaIngresoEN,
                YAHOO.local.calendar.fechaIngreso, true);
        <? } ?>

        YAHOO.local.calendar.fechaIngreso.render();

//      Ingreso a puerto
        YAHOO.local.calendar.ingresoPuerto = new YAHOO.widget.Calendar("idIngPuerto","calIngPuerto");
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.ingresoPuerto.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.ingresoPuerto.selectEvent.subscribe(handlerCalIngPuertoES,
                YAHOO.local.calendar.ingresoPuerto, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.ingresoPuerto.selectEvent.subscribe(handlerCalIngPuertoEN,
                YAHOO.local.calendar.ingresoPuerto, true);
        <? } ?>

        YAHOO.local.calendar.ingresoPuerto.render();

//      DESvencimiento
        YAHOO.local.calendar.DESvencimiento = new YAHOO.widget.Calendar("idDESVencimiento","calDesVencimiento");
        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.DESvencimiento.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.DESvencimiento.selectEvent.subscribe(handlerCalDesVencimientoES,
                YAHOO.local.calendar.DESvencimiento, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.DESvencimiento.selectEvent.subscribe(handlerCalDesVencimientoEN,
                YAHOO.local.calendar.DESvencimiento, true);
        <? } ?>

        YAHOO.local.calendar.DESvencimiento.render();

//       DESpresentado
        YAHOO.local.calendar.DESpresentado = new YAHOO.widget.Calendar("idDESPresentado","calDesPresentado");
        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.DESpresentado.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.DESpresentado.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.DESpresentado.selectEvent.subscribe(handlerCalDESpresentadoES,
                YAHOO.local.calendar.DESpresentado, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.DESpresentado.selectEvent.subscribe(handlerCalDESpresentadoEN,
                YAHOO.local.calendar.DESpresentado, true);
        <? } ?>

        YAHOO.local.calendar.DESpresentado.render();

//       DESsalido
        YAHOO.local.calendar.DESsalido = new YAHOO.widget.Calendar("idDESSalido","calDESsalido");
        YAHOO.local.calendar.DESsalido.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.DESsalido.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.DESsalido.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.DESsalido.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.DESsalido.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.DESsalido.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.DESsalido.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.DESsalido.selectEvent.subscribe(handlerCalDESsalidoES,
                YAHOO.local.calendar.DESsalido, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.DESsalido.selectEvent.subscribe(handlerCalDESsalidoEN,
                YAHOO.local.calendar.DESsalido, true);
        <? } ?>

        YAHOO.local.calendar.DESsalido.render();

//       DEScargado
        YAHOO.local.calendar.DEScargado = new YAHOO.widget.Calendar("idDESCargado","calDEScargado");
        YAHOO.local.calendar.DEScargado.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.DEScargado.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.DEScargado.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.DEScargado.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.DEScargado.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.DEScargado.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.DEScargado.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.DEScargado.selectEvent.subscribe(handlerCalDEScargadoES,
                YAHOO.local.calendar.DEScargado, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.DEScargado.selectEvent.subscribe(handlerCalDEScargadoEN,
                YAHOO.local.calendar.DEScargado, true);
        <? } ?>

        YAHOO.local.calendar.DEScargado.render();

//       DEsfechaFactura
        YAHOO.local.calendar.DEsfechaFactura = new YAHOO.widget.Calendar("idDESFechaFactura","calDEsfechaFactura");
        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MDY_DAY_POSITION", 1);
        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MDY_MONTH_POSITION", 2);
        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MDY_YEAR_POSITION", 3);
        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("DATE_FIELD_DELIMITER", "-");

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MD_DAY_POSITION", 1);
        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MD_MONTH_POSITION", 2);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MONTHS_SHORT",
            [
                "<?= $this->language->_("Ene")?>",
                "<?= $this->language->_("Feb")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Abr")?>",
                "<?= $this->language->_("May")?>",
                "<?= $this->language->_("Jun")?>",
                "<?= $this->language->_("Jul")?>",
                "<?= $this->language->_("Ago")?>",
                "<?= $this->language->_("Sep")?>",
                "<?= $this->language->_("Oct")?>",
                "<?= $this->language->_("Nov")?>",
                "<?= $this->language->_("Dic")?>"
            ]);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("MONTHS_LONG",
            [
                "<?= $this->language->_("Enero")?>",
                "<?= $this->language->_("Febrero")?>",
                "<?= $this->language->_("Marzo")?>",
                "<?= $this->language->_("Abril")?>",
                "<?= $this->language->_("Mayo")?>",
                "<?= $this->language->_("Junio")?>",
                "<?= $this->language->_("Julio")?>",
                "<?= $this->language->_("Agosto")?>",
                "<?= $this->language->_("Septiembre")?>",
                "<?= $this->language->_("Octubre")?>",
                "<?= $this->language->_("Noviembre")?>",
                "<?= $this->language->_("Diciembre")?>"
            ]);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("WEEKDAYS_1CHAR",
            [
                "<?= $this->language->_("D")?>",
                "<?= $this->language->_("L")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("M")?>",
                "<?= $this->language->_("J")?>",
                "<?= $this->language->_("V")?>",
                "<?= $this->language->_("S")?>"
            ]);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("WEEKDAYS_SHORT",
            [
                "<?= $this->language->_("Do")?>",
                "<?= $this->language->_("Lu")?>",
                "<?= $this->language->_("Ma")?>",
                "<?= $this->language->_("Mi")?>",
                "<?= $this->language->_("Ju")?>",
                "<?= $this->language->_("Vi")?>",
                "<?= $this->language->_("Sa")?>"
            ]);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("WEEKDAYS_MEDIUM",
            [
                "<?= $this->language->_("Dom")?>",
                "<?= $this->language->_("Lun")?>",
                "<?= $this->language->_("Mar")?>",
                "<?= $this->language->_("Mie")?>",
                "<?= $this->language->_("Jue")?>",
                "<?= $this->language->_("Vie")?>",
                "<?= $this->language->_("Sab")?>"
            ]);

        YAHOO.local.calendar.DEsfechaFactura.cfg.setProperty("WEEKDAYS_LONG",
            [
                "<?= $this->language->_("Domingo")?>",
                "<?= $this->language->_("Lunes")?>",
                "<?= $this->language->_("Martes")?>",
                "<?= $this->language->_("Miércoles")?>",
                "<?= $this->language->_("Jueves")?>",
                "<?= $this->language->_("Viernes")?>",
                "<?= $this->language->_("Sábado")?>"
            ]);

        <? if ($this->language->getLocale() == 'es') { ?>
            YAHOO.local.calendar.DEsfechaFactura.selectEvent.subscribe(handlerCalDEsfechaFacturaES,
                YAHOO.local.calendar.DEsfechaFactura, true);
        <? } else if ($this->language->getLocale() == 'en') {?>
            YAHOO.local.calendar.DEsfechaFactura.selectEvent.subscribe(handlerCalDEsfechaFacturaEN,
                YAHOO.local.calendar.DEsfechaFactura, true);
        <? } ?>

        YAHOO.local.calendar.DEsfechaFactura.render();

    }

    YAHOO.util.Event.onDOMReady(YAHOO.local.calendar.init);
</script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<div class="cformulario">
    <?= $this->importacionModForm ?>
</div>

<div id="calFechaIngreso" style="display:none;" class="ccalfechaingreso"></div>
<div id="calVencimiento" style="display:none;" class="ccalvencimiento"></div>
<div id="calIngPuerto" style="display:none;" class="ccalingpuerto"></div>
<div id="calPerPre" style="display:none;" class="ccalperpre"></div>
<div id="calDesVencimiento" style="display:none;" class="ccalfecfac"></div>
<div id="calDesPresentado" style="display:none;" class="ccalfecfac"></div>
<div id="calDESsalido" style="display:none;" class="ccalfecfac"></div>
<div id="calDEScargado" style="display:none;" class="ccalfecfac"></div>
<div id="calDEsfechaFactura" style="display:none;" class="ccalfecfac"></div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">		

        var mySchema = ["Resultset.Result","data","id"];
		
	// banderas
        var dataBanderas = new YAHOO.widget.DS_XHR("/user/banderas/getdata/", mySchema);
        dataBanderas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteBanderas = new YAHOO.widget.AutoComplete("idnameBandera", "idbanderasautocomplete", dataBanderas);

	// clientes
	var dataClientes = new YAHOO.widget.DS_XHR("/user/clientes/getdata/", mySchema);
        dataClientes.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteClientes = new YAHOO.widget.AutoComplete("idnameCliente", "idclientesautocomplete", dataClientes);

	// transportes
	var dataTransportes = new YAHOO.widget.DS_XHR("/user/transportes/getdata/", mySchema);
        dataTransportes.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteTransportes = new YAHOO.widget.AutoComplete("idnameTransporte", "idtransportesautocomplete", dataTransportes);
		
	// monedas
	var dataMonedas = new YAHOO.widget.DS_XHR("/user/monedas/getdata/", mySchema);
        dataMonedas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteMonedas = new YAHOO.widget.AutoComplete("idnameMoneda", "idmonedasautocomplete", dataMonedas);

	// cargas
	var dataCargas = new YAHOO.widget.DS_XHR("/user/cargas/getdata/", mySchema);
        dataCargas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteCargas = new YAHOO.widget.AutoComplete("idnameCarga", "idcargasautocomplete", dataCargas);
		
	// destinaciones
	var dataDestinaciones = new YAHOO.widget.DS_XHR("/user/destinaciones/getdata/", mySchema);
        dataDestinaciones.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteDestinaciones = new YAHOO.widget.AutoComplete("idnameDestinacion", "iddestautocomplete", dataDestinaciones);

	// OPPS
	var dataOpps = new YAHOO.widget.DS_XHR("/user/opps/getdata/", mySchema);
        dataOpps.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteOpps = new YAHOO.widget.AutoComplete("idnameOpp", "idoppsautocomplete", dataOpps);

	// GIROS
	var dataGiros = new YAHOO.widget.DS_XHR("/user/giros/getdata/", mySchema);
        dataGiros.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteGiros = new YAHOO.widget.AutoComplete("idnameGiro", "idgirosautocomplete", dataGiros);
	
	// validacion
	var frmvalidator  = new Validator("form");

	//habilito alert con mensajes
	frmvalidator.EnableOnPageErrorDisplaySingleBox();
	frmvalidator.EnableMsgsTogether();
	
	frmvalidator.addValidation("idnameOrden","req","<?= $this->language->_("*Ingrese el número de orden")?>");
	frmvalidator.addValidation("idnameOrden","numeric","<?= $this->language->_("*La órden debe ser únicamente numérica")?>");
			  
	frmvalidator.addValidation("idnameTransporte","req","<?= $this->language->_("*Elija un transporte")?>");
	frmvalidator.addValidation("idnameTransporte","alnum_s ","<?= $this->language->_("*El transporte debe ser alfanumérico")?>");
			  
	frmvalidator.addValidation("idnameCliente","req","<?= $this->language->_("*Elija un cliente")?>");
	frmvalidator.addValidation("idnameCliente","alpha_s","<?= $this->language->_("*El cliente debe ser alfanumérico")?>");

	frmvalidator.addValidation("idnameBandera","req","<?= $this->language->_("*Elija una Bandera")?>");
	frmvalidator.addValidation("idnameBandera","alpha_s","<?= $this->language->_("*La bandera debe contener sólo letras")?>");

	frmvalidator.addValidation("idnameMoneda","req","<?= $this->language->_("*Elija una moneda")?>");
	frmvalidator.addValidation("idnameMoneda","alpha_s","<?= $this->language->_("*La moneda debe contener sólo letras")?>");

	frmvalidator.addValidation("idnameDestinacion","req","<?= $this->language->_("*Elija una destinación")?>");
	frmvalidator.addValidation("idnameDestinacion","alpha_s","<?= $this->language->_("*La destinación debe contener sólo letras")?>");

	frmvalidator.addValidation("idnameCarga","req","<?= $this->language->_("*Elija una carga")?>");
	frmvalidator.addValidation("idnameCarga","alnum","<?= $this->language->_("*La carga debe contener sólo letras")?>");

	frmvalidator.addValidation("referencia","req","<?= $this->language->_("*Ingrese una referencia")?>");
	frmvalidator.addValidation("referencia","alnum_s","<?= $this->language->_("*La referencia debe ser alfanumérica")?>");

	frmvalidator.addValidation("idFechaIngreso","req","<?= $this->language->_("*Ingrese una fecha de ingreso")?>");
	frmvalidator.addValidation("idFechaIngreso","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$", "<?= $this->language->_("*La fecha de ingreso es inválida")?>");

	frmvalidator.addValidation("desMercaderias","req","<?= $this->language->_("*Ingrese una descripción de mercadería")?>");
	frmvalidator.addValidation("desMercaderias","alnum_s","<?= $this->language->_("*La descripción de mercadería debe ser alfanumérica")?>");

	frmvalidator.addValidation("valorFactura","req","<?= $this->language->_("*Ingrese un valor de factura")?>");
	frmvalidator.addValidation("valorFactura","dec","<?= $this->language->_("*El valor de factura debe ser numérico")?>");

	frmvalidator.addValidation("DESnroDoc","req","<?= $this->language->_("*Ingrese un número de despacho")?>");
	frmvalidator.addValidation("DESnroDoc","alnum","<?= $this->language->_("*El número de despacho debe ser numérico")?>");

	frmvalidator.addValidation("docTransporte","req","<?= $this->language->_("*Ingrese una documentacion de transporte")?>");
	frmvalidator.addValidation("docTransporte","alnum_s","<?= $this->language->_("*La documentacion de transporte debe ser alfanumérica")?>");

	frmvalidator.addValidation("DESdeclaracion","req","<?= $this->language->_("*Ingrese una descripción de declaracion")?>");
	frmvalidator.addValidation("DESdeclaracion","alnum_s","<?= $this->language->_("*La descripción de declaracion debe ser alfanumérica")?>");

	frmvalidator.addValidation("idDESSalido","req","<?= $this->language->_("*Ingrese la fecha del despacho salido")?>");
	frmvalidator.addValidation("idDESSalido","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha del despacho salido es inválida")?>");

	frmvalidator.addValidation("idDESPresentado","req","<?= $this->language->_("*Ingrese la fecha del despacho presentado")?>");
	frmvalidator.addValidation("idDESPresentado","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha del despacho presentado es inválida")?>");

	frmvalidator.addValidation("idDESCargado","req","<?= $this->language->_("*Ingrese la fecha del despacho cargado")?>");
	frmvalidator.addValidation("idDEScargado","regexp=^(0[1-9]|[12][0-9]|3[01])\-(0[1-9]|[12][0-9]|3[01])\-(19|20)([0-9]{2})$","<?= $this->language->_("*La fecha del despacho cargado es inválida")?>");		

</script>
