<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->escape($this->error) ?></div>
<? } ?>

<div class="busqueda">
    <?= $this->exportacionSearchForm ?>
</div>

<div id="divlistado" class="clistado">
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $exportacion) { ?>
            <?= $this->escape($this->language->_("Órden")) . ": " . $this->escape($exportacion->orden()) ?> <br />
            <?= $this->escape($this->language->_("Transporte")) . ": " . $this->escape($exportacion->codTransporteName()) ?> <br />
            <?= $this->escape($this->language->_("Cliente")) . ": " . $this->escape($exportacion->codClienteName()) ?> <br />
            <?= $this->escape($this->language->_("Destino")) . ": " . $this->escape($exportacion->codDestinacionName()) ?> <br />
            <?= $this->escape($this->language->_("Carga")) . ": " . $this->escape($exportacion->codCargaName()) ?> <br />
            <?= $this->escape($this->language->_("Fecha de Ingreso")) . ": " . $this->escape($exportacion->fechaIngreso()) ?> <br /><br /><br />
        <? } ?>
    <? } ?>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<br />
<a href="<?= "/mobile/user/index" ?>"> <?= $this->escape($this->language->_("Menu Principal"))?> </a><br />
<a href="<?= "/mobile/index/logout" ?>"> <?= $this->escape($this->language->_("Logout"))?> </a>
