<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <? foreach ($this->message as $msg) { ?>
        <div class="msg"><?= $msg ?></div>
    <? } ?>
<? } ?>
<div class="busqueda">
    <?= $this->userSearchForm ?>
</div>   
<div id="divlistusers" class="clistado">
    <table id="tableusers">
        <thead>
            <tr>
                <th> <?= $this->language->_("Nombre") ?> </th>
                <th> <?= $this->language->_("Usuario") ?> </th>
                <th> <?= $this->language->_("E-mail") ?> </th>
                <th> <?= $this->language->_("Idioma") ?> </th>
                <th> <?= $this->language->_("CSS") ?> </th>
                <th> <?= $this->language->_("Modificar") ?> </th>
                <th> <?= $this->language->_("Eliminar") ?> </th>
            </tr>
        </thead>
        <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $user) { ?>
            <tr>
                <td> <?= $user->name() ?> </td>
                <td> <?= $user->user() ?> </td>
                <td> <?= $user->email() ?> </td>
                <td> <?= $user->language() ?> </td>
                <td> <?= $user->codCssName() ?> </td>
                <td>
                    <a href="<?= "/admin/users/modusers/id/" . $user->id()?>"> <?= $this->language->_("Modificar") ?> </a>
                </td>
                <td>
                    <a href="<?= "/admin/users/removeusers/id/" . $user->id()?>"> <?= $this->language->_("Eliminar") ?> </a>
                </td>
            </tr>
            <? } ?>
        <? } ?>
        </tbody>
        </table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>
                
<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:" <?= $this->language->_("Nombre") ?>",sortable:false},
            {key:"user",label:" <?= $this->language->_("Usuario") ?>", sortable:false},
            {key:"email",label:" <?= $this->language->_("E-mail") ?>", sortable:false},
            {key:"language",label:" <?= $this->language->_("Idioma") ?>", sortable:false},
            {key:"css",label:" <?= $this->language->_("CSS") ?>", sortable:false},
            {key:"modify",label:" <?= $this->language->_("Modificar") ?>", sortable:false},
            {key:"eliminate",label:" <?= $this->language->_("Eliminar") ?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tableusers"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields:
            [
                {key:"name"},
                {key:"user"},
                {key:"email"},
                {key:"language"},
                {key:"css"},
                {key:"modify"},
                {key:"eliminate"}
            ]
        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistusers", myColumnDefs, this.myDataSource,
                {}
        );
        
        function cambiaBusqueda(e) {
            var x = location.protocol + '//' + location.host + location.pathname;
            var y = "";
            var sortby_prev = "";
            var sort_prev = "";
            var sort_act;
            
            <? if (isset($_GET["consulta"])) { ?>
                y = "<?= $this->escape($_GET["consulta"]) ?>";
            <? } ?>
            
            <? if (isset($_GET["sortby"])) { ?>
                sortby_prev = "<?= $this->escape($_GET["sortby"]) ?>";
            <? } ?>
                        
            <? if (isset($_GET["sort"])) { ?>
                sort_prev = "<?= $this->escape($_GET["sort"]) ?>";
            <? } ?>
                        
            if (this.getColumn(e.target) == "Column instance 0")
            {
                if (sortby_prev == "name") 
                {
                    if (sort_prev == "asc")
                        sort_act = "desc";
                    else
                        sort_act = "asc";
                }
                else
                {
                    sort_act = "asc";
                }
                window.location = x + "?consulta=" + y + "&sortby=name" + "&sort=" + sort_act;
            }
            else if (this.getColumn(e.target) == "Column instance 1")
            {
                if (sortby_prev == "user") 
                {
                    if (sort_prev == "asc")
                        sort_act = "desc";
                    else
                        sort_act = "asc";
                }
                else
                {
                    sort_act = "asc";
                }
                window.location = x + "?consulta=" + y + "&sortby=user" + "&sort=" + sort_act;
            }
        }
        this.myDataTable.subscribe("theadCellClickEvent", cambiaBusqueda);
    };
});
</script>
