<? if (isset($this->error)) { ?>
    <div class="error_fatal"><?= $this->escape($this->error) ?></div>
    <div id="errmsg"></div>
    <script languaje="javascript">
        var time=0;
        showAlert("errmsg", { width:"620px", modal:true, visible:true, underlay:"shadow", fixedcenter:true, constraintoviewport:true, draggable:false } , "Error Fatal", "<div id='diverror' class='error_fatal'><?= $this->escape($this->language->_($this->error)) ?></div><br><div id='idtimeerror'></div>", "Trifiori");
        setInterval (function (){if (time==5){document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando al Home...'))?>";window.location.href = "/";}else{ document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando en'))?> " + (5-time); time++;}}, 1000);
    </script>
<? } else { ?>
            <? if (isset($this->message)) { ?>
                <div class="msg"><?= $this->escape($this->message) ?></div>
                        <? } ?>
<div class="cformulario">
	<?= $this->cargaAddForm ?>
</div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">
    // validacion
    var frmvalidator  = new Validator("form");

    //habilito alert con mensajes
    frmvalidator.EnableOnPageErrorDisplaySingleBox();
    frmvalidator.EnableMsgsTogether();

    frmvalidator.addValidation("cantBultos","req","<?= $this->language->_("*Ingrese la cantidad de bultos")?>");
    frmvalidator.addValidation("cantBultos","num","<?= $this->language->_("*La cantidad de bultos debe ser numérica")?>");

    frmvalidator.addValidation("tipoEnvase","req","<?= $this->language->_("*Ingrese un tipo de envase")?>");

    frmvalidator.addValidation("unidad","req","<?= $this->language->_("*Ingrese una unidad")?>");

    frmvalidator.addValidation("peso","req","<?= $this->language->_("*Ingrese un peso")?>");
    frmvalidator.addValidation("peso","dec","<?= $this->language->_("*El peso debe ser decimal")?>");

    frmvalidator.addValidation("nroPaquete","req","<?= $this->language->_("*Ingrese un número de paquete")?>");
    frmvalidator.addValidation("nroPaquete","alnum","<?= $this->language->_("*El número de paquete debe ser alfanumérico")?>");

</script>
<? } ?>
