<div class='cInputsTable'>
	<label for="cColBultos"><?= $this->language->_("Cantidad Bultos")?></label>
	<input type='checkbox' id="cColBultos" name="cColBultos" checked>  
	<label for="cColTipoenvase"><?= $this->language->_("Tipo de Envase")?></label>
	<input type='checkbox' id="cColTipoenvase" name="cColTipoenvase" checked> 
	<label for="cColPeso"><?= $this->language->_("Peso")?></label>
	<input type='checkbox' id="cColPeso" name="cColPeso" checked> 
	<label for="cColnropaq"><?= $this->language->_("Número de Paquete")?></label>
	<input type='checkbox' id="cColnropaq" name="cColnropaq" checked> 
	<label for="cColMarcayum"><?= $this->language->_("Marca y número")?></label>
	<input type='checkbox' id="cColMarcayum" name="cColMarcayum" checked> 
	<label for="cColImco"><?= $this->language->_("Merc. IMCO")?></label>
	<input type='checkbox' id="cColImco" name="cColImco" checked>  
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Cantidad Bultos")?> </th>
            <th> <?= $this->language->_("Tipo de Envase")?> </th>
            <th> <?= $this->language->_("Peso")?> </th>
            <th> <?= $this->language->_("Unidad")?> </th>
            <th> <?= $this->language->_("Número de Paquete")?> </th>
            <th> <?= $this->language->_("Marca y número")?> </th>
            <th> <?= $this->language->_("Merc. IMCO")?> </th>
            <th> <?= $this->language->_("Modificar")?> </th>
            <th> <?= $this->language->_("Eliminar")?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $carga) { ?>
        <tr> 
            <td> <?= $carga->cantBultos() ?> </td>
            <td> <?= $carga->tipoEnvase() ?> </td>
            <td> <?= $carga->peso() ?> </td>
            <td> <?= $carga->unidad() ?> </td>
            <td> <?= $carga->nroPaquete() ?> </td>
            <td> <?= $carga->marcaYnum() ?> </td>
            <td> <?= $carga->mercIMCO() ?> </td>
            <td>
                <a href="<?= "/user/cargas/modcargas/id/" . $carga->id()?>"> <?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/cargas/removecargas/id/" . $carga->id()?>"> <?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>
<?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"bultos",label:" <?= $this->language->_("Cantidad Bultos")?> ", sortable:true},
            {key:"tipoenvase",label:" <?= $this->language->_("Tipo de Envase")?> ", sortable:true},
            {key:"peso",label:" <?= $this->language->_("Peso")?> ", sortable:true},
            {key:"unidad",label:" <?= $this->language->_("Unidad")?> ", sortable:true},
            {key:"nropaq",label:" <?= $this->language->_("Número de Paquete")?> ", sortable:true},
            {key:"marcayum",label:" <?= $this->language->_("Marca y número")?> ", sortable:true},
            {key:"imco",label:" <?= $this->language->_("Merc. IMCO")?> ", sortable:true},
            {key:"mod",label:" <?= $this->language->_("Modificar")?> ", sortable:false},
            {key:"elim",label:" <?= $this->language->_("Eliminar")?> ", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema =
        {
            fields:
            [
                {key:"bultos"},
                {key:"tipoenvase"},
                {key:"peso"},
                {key:"unidad"},
                {key:"nropaq"},
                {key:"marcayum"},
                {key:"imco"},
                {key:"mod"},
                {key:"elim"}
            ]
        };

        var myDT = this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true});
					
		YAHOO.util.Event.addListener("cColBultos", "click", function (e){
									   if (document.getElementById('cColBultos').checked)
										  myDT.showColumn("bultos");
									   else
										  myDT.hideColumn("bultos");
									});

		YAHOO.util.Event.addListener("cColTipoenvase", "click", function (e){
									   if (document.getElementById('cColTipoenvase').checked)
										  myDT.showColumn("tipoenvase");
									   else
										  myDT.hideColumn("tipoenvase");
									});
	
		YAHOO.util.Event.addListener("cColPeso", "click", function (e){
									   if (document.getElementById('cColPeso').checked)
										  myDT.showColumn("peso");
									   else
										  myDT.hideColumn("peso");
									});
		YAHOO.util.Event.addListener("cColnropaq", "click", function (e){
									   if (document.getElementById('cColnropaq').checked)
										  myDT.showColumn("nropaq");
									   else
										  myDT.hideColumn("nropaq");
									});
		YAHOO.util.Event.addListener("cColMarcayum", "click", function (e){
									   if (document.getElementById('cColMarcayum').checked)
										  myDT.showColumn("marcayum");
									   else
										  myDT.hideColumn("marcayum");
									});
		YAHOO.util.Event.addListener("cColIva", "click", function (e){
									   if (document.getElementById('cColIva').checked)
										  myDT.showColumn("iva");
									   else
										  myDT.hideColumn("iva");
									});
		YAHOO.util.Event.addListener("cColImco", "click", function (e){
									   if (document.getElementById('cColImco').checked)
										  myDT.showColumn("imco");
									   else
										  myDT.hideColumn("imco");
									});

    };
});
</script>
