<script type="text/javascript">
        var myColumnDefs = [
            {key:"bultos",label:" <?= $this->language->_("Cantidad Bultos")?> ", sortable:true},
            {key:"tipoenvase",label:" <?= $this->language->_("Tipo de Envase")?> ", sortable:true},
            {key:"peso",label:" <?= $this->language->_("Peso")?> ", sortable:true},
            {key:"unidad",label:" <?= $this->language->_("Unidad")?> ", sortable:true},
            {key:"nropaq",label:" <?= $this->language->_("Número de Paquete")?> ", sortable:true},
            {key:"marcayum",label:" <?= $this->language->_("Marca y número")?> ", sortable:true},
            {key:"imco",label:" <?= $this->language->_("Merc. IMCO")?> ", sortable:true},
            {key:"mod",label:" <?= $this->language->_("Modificar")?> ", sortable:false},
            {key:"elim",label:" <?= $this->language->_("Eliminar")?> ", sortable:false}
        ];

var hideLabel = "<?= $this->language->_("Oculto")?>";
var showLabel = "<?= $this->language->_("Visible")?>";
var closeLabel = "<?= $this->language->_("Cerrar")?>";
</script>
<script type="text/javascript" src="/js/init_listcargas.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<? if (isset($this->message)) { ?>
    <? foreach ($this->message as $msg) { ?>
        <div class="msg"><?= $msg ?></div>
    <? } ?>
<? } ?>
<div class="busqueda">
    <?= $this->cargaSearchForm ?>
</div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->language->_("Opciones de la tabla")?></a></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr>
            <th> <?= $this->language->_("Cantidad Bultos")?> </th>
            <th> <?= $this->language->_("Tipo de Envase")?> </th>
            <th> <?= $this->language->_("Peso")?> </th>
            <th> <?= $this->language->_("Unidad")?> </th>
            <th> <?= $this->language->_("Número de Paquete")?> </th>
            <th> <?= $this->language->_("Marca y número")?> </th>
            <th> <?= $this->language->_("Merc. IMCO")?> </th>
            <th> <?= $this->language->_("Modificar")?> </th>
            <th> <?= $this->language->_("Eliminar")?> </th>
        </tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $carga) { ?>
        <tr> 
            <td> <?= $carga->cantBultos() ?> </td>
            <td> <?= $carga->tipoEnvase() ?> </td>
            <td> <?= $carga->peso() ?> </td>
            <td> <?= $carga->unidad() ?> </td>
            <td> <?= $carga->nroPaquete() ?> </td>
            <td> <?= $carga->marcaYnum() ?> </td>
            <td> <?= $carga->mercIMCO() ?> </td>
            <td>
                <a href="<?= "/user/cargas/modcargas/id/" . $carga->id()?>"> <?= $this->language->_("Modificar")?> </a>
            </td>
            <td>
                <a href="<?= "/user/cargas/removecargas/id/" . $carga->id()?>"> <?= $this->language->_("Eliminar")?> </a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->language->_("Seleccione las columnas que desea ver:")?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>

