<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <link rel="stylesheet" href="/css/adduser.css" type="text/css" media="screen,projection"/>
    <?= $this->headTitle() ?>
</head>
<body>
    <div class="container">
        <!-- TODO: Hacer el buscador y ubicarlo bien en la página!  -->
        <?= $this->action('finduser', 'moduser', 'admin') ?>

        <div class="block">
            <div class="column span-6 last">
                <div id="login" class="box">
                    <?= $this->action('listuser', 'moduser', 'admin') ?>
                </div>
            </div>


        <div class="block">
            <div id="footer" class="span-24">
                <p>Copyright &copy; 2008 Trifiori</p>
            </div>
        </div>
    </div>
</body>
</html>
