<? if ($this->showForm) { ?>
    <? if (isset($this->failedAddUser)) { ?>
        <p class="error"> <?= $this->failedAddUser ?>.</p>
    <? } ?>
    <?= $this->modForm ?>
    <?= $this->headTitle() ?>
<? }else { ?>
<div id="markup">
    <table id="listado">
        <thead>
            <tr> <th>ID</th> <th>Nombre</th> <th>Usuario</th> <th>Idioma</th><th>Modificar</th><th>Eliminar</th> </tr>
        </thead>
        <tbody>
            <? foreach($this->users as $user) { ?>
            <tr> <td> <?= $user->id() ?> </td>
                <td> <?= $user->name() ?> </td>
                <td> <?= $user->user() ?> </td>
                <td> <?= $user->language() ?> </td>
                <td> <a href="<?= $this->baseUrl . "/listuser/id/".$user->id()?>">x</a> </td>
                <td> <a href="<?= $this->baseUrl . "/removeuser/id/".$user->id()?>">x</a> </td>
            </tr>
            <? } ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"id",label:"ID",sortable:true},
            {key:"nombre",label:"Nombre", sortable:true},
            {key:"usuario",label:"Usuario",sortable:true},
            {key:"idioma",label:"Idioma",sortable:true},
			{key:"modificar",label:"Modificar",sortable:true},
			{key:"eliminar",label:"Eliminar",sortable:true}
        ];
        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("listado"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [{key:"id"},
                    {key:"nombre"},
                    {key:"usuario"},
                    {key:"idioma"},
					{key:"modificar"},
					{key:"eliminar"}
            ]
        };

        this.myDataTable = new YAHOO.widget.DataTable("markup", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"id",dir:"desc"}}
        );
    };
});
</script>

<? } ?>