<table class="bordered">
    <thead>
        <tr> <th>ID</th> <th>Nombre</th> <th>Usuario</th> <th>Idioma</th> </tr>
    </thead>
    <tbody>
        <? foreach($this->users as $user) { ?>
        <tr> <td> <?= $user->id() ?> </td>
             <td> <?= $user->name() ?> </td>
             <td> <?= $user->user() ?> </td>
             <td> <?= $user->language() ?> </td>
             <td> <a href="<?= $this->baseUrl . "/removeuser/id/".$user->id()?>">Eliminar</a> </td>
        </tr>
        <? } ?>
    </tbody>
</table>