<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>
	
	<!-- Standard reset and fonts -->

	<link rel="stylesheet" type="text/css" href="/yui/build/reset/reset.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/fonts/fonts.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/fonts/fonts-min.css" />
	<link rel="stylesheet" type="text/css" href="/yui/build/datatable/assets/skins/sam/datatable.css" />
	
	<!-- CSS for Menu -->
	<link rel="stylesheet" type="text/css" href="/yui/build/menu/assets/skins/sam/menu.css"> 
	<link rel="stylesheet" href="/css/panelAdmin.css" type="text/css" media="screen,projection"/>
	
	<!-- Page-specific styles -->
	<style type="text/css">
	#filemenu.visible .yuimenuitemlabel,
	#editmenu.visible .yuimenuitemlabel {
		*zoom: 1;
		}
		
    body {
    	margin:0;
		padding:0;
	}
	</style>
	
	<!-- Dependency source files -->
	<script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
	<script type="text/javascript" src="/yui/build/element/element-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datasource/datasource-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datatable/datatable-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/utilities/utilities.js"></script>
	<script type="text/javascript" src="/yui/build/container/container.js"></script>
	<script type="text/javascript" src="/js/handlers.js"></script>
	<script type="text/javascript" src="/js/txtmenus.js"></script>
	<!-- Menu source file -->
<script type="text/javascript" src="/yui/build/menu/menu.js"></script>

        <script type="text/javascript">

            /*
                 Initialize and render the MenuBar when the page's DOM is ready 
                 to be scripted.
            */
			
            YAHOO.util.Event.onDOMReady(function () {
                /*
                     Define an array of object literals, each containing 
                     the data necessary to create the items for a MenuBar.
                */
                

                /*
                     Instantiate a MenuBar:  The first argument passed to the 
                     constructor is the id of the element to be created; the 
                     second is an object literal of configuration properties.
                */

                var oMenuBar = new YAHOO.widget.MenuBar("mymenubar", { 
                                                            lazyload: true, 
                                                            itemdata: txtmenuadminspa 
                                                            });


                /*
                     Since this MenuBar instance is built completely from 
                     script, call the "render" method passing in a node 
                     reference for the DOM element that its should be 
                     appended to.
                */

                oMenuBar.render(document.body);


                // Add a "show" event listener for each submenu.
                function onSubmenuShow() {
					var oIFrame,
						oElement,
                        nOffsetWidth;
					// Keep the left-most submenu against the left edge of the browser viewport
					if (this.id == "yahoo") {
						YAHOO.util.Dom.setX(this.element, 0);
						oIFrame = this.iframe;            
						if (oIFrame) {				
							YAHOO.util.Dom.setX(oIFrame, 0);
						}
						this.cfg.setProperty("x", 0, true);
					}


					/*
						Need to set the width for submenus of submenus in IE to prevent the mouseout 
						event from firing prematurely when the user mouses off of a MenuItem's 
						text node.
					*/

                    if ((this.id == "filemenu" || this.id == "editmenu") && YAHOO.env.ua.ie) {
                        oElement = this.element;
                        nOffsetWidth = oElement.offsetWidth;
                        /*
                            Measuring the difference of the offsetWidth before and after
                            setting the "width" style attribute allows us to compute the 
                            about of padding and borders applied to the element, which in 
                            turn allows us to set the "width" property correctly.
                        */
                        oElement.style.width = nOffsetWidth + "px";
                        oElement.style.width = (nOffsetWidth - (oElement.offsetWidth - nOffsetWidth)) + "px";
                    }

                }
                
                // Subscribe to the "show" event for each submenu
                oMenuBar.subscribe("show", onSubmenuShow);
				
				/*
                var oPanel = new YAHOO.widget.Panel("exampleinfo", { constraintoviewport: true, fixedcenter: true, width: "400px", zIndex: 1});
                
                oPanel.setHeader("Application Menubar Example");
                oPanel.setBody("Pendejo trolo.");

                oPanel.render(document.body);
				*/
            	
            });
		

        </script>

    </head>
	<body class="yui-skin-sam">
		<div class="container">
			<!-- TODO: Hacer el buscador y ubicarlo bien en la página!  -->


	
        <? if (isset($this->failedAddUser)) { ?>
            <p class="error"> <?= $this->failedAddUser ?>.</p>
        <? } ?>
        <?= $this->modForm ?>
        <?= $this->headTitle() ?>
			<div id="footer" class="cfooter">
					<p>Copyright &copy; 2008 Trifiori</p>
			</div>
		</div>
	</body>
</html>
