<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->monedaSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr> <th>Nombre</th> <th>Descripción</th> <th>Modificar</th> <th>Eliminar</th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $moneda) { ?>
        <tr> 
            <td> <?= $moneda->name() ?> </td>
            <td> <?= $moneda->longName() ?> </td>
            <td>
                <a href="<?= "/user/monedas/modmonedas/id/" . $moneda->id()?>">Modificar</a>
            </td>
			<td>
                <a href="<?= "/user/monedas/removemonedas/id/" . $moneda->id()?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"Nombre", sortable:true},
			{key:"desc",label:"Descripcion", sortable:true},
			{key:"mod",label:"Modificar", sortable:false},
			{key:"elim",label:"Eliminar", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [{key:"name"},
					{key:"desc"},
					{key:"mod"},
					{key:"elim"}]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true}
        );
    };
});
</script>
