<script type="text/javascript">
var myColumnDefs = [
	{key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
	{key:"desc",label:"<?= $this->language->_("Descripción")?>", sortable:true},
	{key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
	{key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}];
</script>
<script type="text/javascript" src="/js/init_listmonedas.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->monedaSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr> <th><?= $this->language->_("Nombre")?> </th> <th><?= $this->language->_("Descripción")?></th> <th><?= $this->language->_("Modificar")?></th> <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $moneda) { ?>
        <tr> 
            <td> <?= $moneda->name() ?> </td>
            <td> <?= $moneda->longName() ?> </td>
            <td>
                <a href="<?= "/user/monedas/modmonedas/id/" . $moneda->id()?>">Modificar</a>
            </td>
			<td>
                <a href="<?= "/user/monedas/removemonedas/id/" . $moneda->id()?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

