<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>


    <!-- Standard reset and fonts -->
    <link rel="stylesheet" type="text/css" href="/yui/build/reset/reset.css">
    <link rel="stylesheet" type="text/css" href="/yui/build/reset-fonts-grids/reset-fonts-grids.css">
    <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/datatable/assets/skins/sam/datatable.css" />
    <!-- CSS for Menu -->
    <link rel="stylesheet" type="text/css" href="/yui/build/menu/assets/skins/sam/menu.css"> 
    <link rel="stylesheet" href="/css/panelAdmin.css" type="text/css" media="screen,projection"/>

    <!-- Dependency source files -->
    <script type="text/javascript" src="/yui/build/utilities/utilities.js"></script>
    <script type="text/javascript" src="/yui/build/container/container.js"></script>
	<script type="text/javascript" src="/yui/build/animation/animation-min.js"></script>
	<script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
	<script type="text/javascript" src="/yui/build/container/container_core-min.js"></script>
	<script type="text/javascript" src="/yui/build/element/element-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datasource/datasource-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datatable/datatable-beta-min.js"></script>

    <script type="text/javascript" src="/js/handlers.js"></script>
    <script type="text/javascript" src="/js/txtmenus.js"></script>
    <script type="text/javascript" src="/js/gen_validatorv31.js"></script>

    <!-- Menu source file -->
    <script type="text/javascript" src="/yui/build/menu/menu.js"></script>
        <script type="text/javascript">
            YAHOO.util.Event.onContentReady("menuadmin", function () {
                var ua = YAHOO.env.ua, oAnim;  // Animation instance
                function onSubmenuBeforeShow(p_sType, p_sArgs) {
                    var oBody,oElement,oShadow,oUL;
                    if (this.parent) {
                        oElement = this.element;
                        oShadow = oElement.lastChild;
                        oShadow.style.height = "0px";
                        if (oAnim && oAnim.isAnimated()) {
                            oAnim.stop();
                            oAnim = null;}
                        oBody = this.body;
                        if (this.parent && !(this.parent instanceof YAHOO.widget.MenuBarItem)) {
                            if (ua.gecko || ua.opera) {
                                oBody.style.width = oBody.clientWidth + "px";
                            }
                            if (ua.ie == 7) {
                                oElement.style.width = oElement.clientWidth + "px";
                            }
                        
                        }
                        oBody.style.overflow = "hidden";
                        oUL = oBody.getElementsByTagName("ul")[0];
                        oUL.style.marginTop = ("-" + oUL.offsetHeight + "px");
                    }
                }

                function onTween(p_sType, p_aArgs, p_oShadow) {
                    if (this.cfg.getProperty("iframe")) {
                        this.syncIframe();
                    }
                
                    if (p_oShadow) {
                        p_oShadow.style.height = this.element.offsetHeight + "px";
                    }
                }

                function onAnimationComplete(p_sType, p_aArgs, p_oShadow) {
                    var oBody = this.body,
                        oUL = oBody.getElementsByTagName("ul")[0];

                    if (p_oShadow) {
                        p_oShadow.style.height = this.element.offsetHeight + "px";
                    }

                    oUL.style.marginTop = "";
                    oBody.style.overflow = "";

                    if (this.parent &&  !(this.parent instanceof YAHOO.widget.MenuBarItem)) {
                        if (ua.gecko || ua.opera) {
                            oBody.style.width = "";
                        }
                        
                        if (ua.ie == 7) {
                            this.element.style.width = "";
                        }
                    }
                }

                function onSubmenuShow(p_sType, p_sArgs) {
                    var oElement,oShadow,oUL;
                
                    if (this.parent) {
                        oElement = this.element;
                        oShadow = oElement.lastChild;
                        oUL = this.body.getElementsByTagName("ul")[0];
                    
                        oAnim = new YAHOO.util.Anim(oUL, 
                            { marginTop: { to: 0 } },
                            .5, YAHOO.util.Easing.easeOut);

                        oAnim.onStart.subscribe(function () {        
                            oShadow.style.height = "100%";
                        });
    
                        oAnim.animate();

                    if (YAHOO.env.ua.ie) {                            
                            oShadow.style.height = oElement.offsetHeight + "px";
                            oAnim.onTween.subscribe(onTween, oShadow, this);
                        }
                        oAnim.onComplete.subscribe(onAnimationComplete, oShadow, this);                    
                    }
                }

                var oMenuBar = new YAHOO.widget.MenuBar("menuadmin", { 
                                                            autosubmenudisplay: true, 
                                                            hidedelay: 750, 
                                                            lazyload: true });
                
                oMenuBar.subscribe("beforeShow", onSubmenuBeforeShow);
                oMenuBar.subscribe("show", onSubmenuShow);

                oMenuBar.render();                      
            });
        </script>
    </head>
    <body class="yui-skin-sam">
	 <div id="yui-main">
                    <div class="yui-b">
                        <!-- start: stack grids here -->
                       <div id="menuadmin" class="yuimenubar yuimenubarnav">
                            <div class="bd">
                                <ul class="first-of-type">
                                    <li class="yuimenubaritem first-of-type"><a class="yuimenubaritemlabel" href="/admin/panel/logout"><?= $this->language->_("Logout")?></a></li>
                                    <li class="yuimenubaritem"><a class="yuimenubaritemlabel" href="#menuusuarios"><?= $this->language->_("Usuarios")?></a>
                                        <div id="menuusuarios" class="yuimenu">
                                            <div class="bd">                    
                                                <ul>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/addusers"><?= $this->language->_("Agregar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Modificar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Borrar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Listado")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="#"><?= $this->language->_("Estadísticas")?></a></li>
                                                </ul>
                                            </div>
                                        </div>                    
                                    </li>
									<li class="yuimenubaritem first-of-type"><a class="yuimenubaritemlabel" href="/admin/log/listlogs"><?= $this->language->_("Últimas modificaciones")?></a></li>
								</ul>            
                            </div>
                        </div>
		      </div>
    </div>
	<?= $this->layout()->content ?>
    </body>
</html>
