<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>


    <!-- Standard reset and fonts -->
    <link rel="stylesheet" type="text/css" href="/yui/build/reset/reset.css">
    <link rel="stylesheet" type="text/css" href="/yui/build/reset-fonts-grids/reset-fonts-grids.css">
    <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/datatable/assets/skins/sam/datatable.css" />
    <!-- CSS for Menu -->

    <script type="text/javascript">
        if (1==1)
            document.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/yui/build/menu/assets/skins/sam/menu.css\" /> ");
    </script>
    <link rel="stylesheet" href="/css/panelAdmin.css" type="text/css" media="screen,projection"/>

    <!-- Dependency source files -->
    <script type="text/javascript" src="/yui/build/utilities/utilities.js"></script>
    <script type="text/javascript" src="/yui/build/container/container.js"></script>
	<script type="text/javascript" src="/yui/build/animation/animation-min.js"></script>
	<script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
	<script type="text/javascript" src="/yui/build/container/container_core-min.js"></script>
	<script type="text/javascript" src="/yui/build/element/element-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datasource/datasource-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datatable/datatable-beta-min.js"></script>

    <script type="text/javascript" src="/js/handlers.js"></script>
    <script type="text/javascript" src="/js/txtmenus.js"></script>
    <script type="text/javascript" src="/js/gen_validatorv31.js"></script>

    <!-- Menu source file -->
    <script type="text/javascript" src="/yui/build/menu/menu.js"></script>
        <script type="text/javascript" src="/js/init_layoutadmin.js"></script>
    </head>
    <body class="yui-skin-sam">
	 <div id="yui-main">
                    <div class="yui-b">
                        <!-- start: stack grids here -->
                       <div id="menuadmin" class="yuimenubar yuimenubarnav">
                            <div class="bd">
                                <ul class="first-of-type">
                                    <li class="yuimenubaritem first-of-type"><a class="yuimenubaritemlabel" href="/admin/panel/logout"><?= $this->language->_("Logout")?></a></li>
                                    <li class="yuimenubaritem"><a class="yuimenubaritemlabel" href="#menuusuarios"><?= $this->language->_("Usuarios")?></a>
                                        <div id="menuusuarios" class="yuimenu">
                                            <div class="bd">                    
                                                <ul>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/addusers"><?= $this->language->_("Agregar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Modificar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Borrar usuario")?></a></li>
                                                    <li class="yuimenuitem"><a class="yuimenuitemlabel" href="/admin/users/listusers"><?= $this->language->_("Listado")?></a></li>
                                                </ul>
                                            </div>
                                        </div>                    
                                    </li>
									<li class="yuimenubaritem first-of-type"><a class="yuimenubaritemlabel" href="/admin/log/listlogs"><?= $this->language->_("Últimas modificaciones")?></a></li>
								</ul>            
                            </div>
                        </div>
		      </div>
    </div>
	<?= $this->layout()->content ?>
    </body>
</html>
