<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>

<html>
<head>
    <?= $this->headTitle() ?>
    <link rel="stylesheet" href="/css/login.css" type="text/css" media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css" />
    <script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
    <script type="text/javascript" src="/yui/build/container/container-min.js"></script>
    <script type="text/javascript" src="/js/handlers.js"></script>
</head>
<body class="yui-skin-sam">
    <?= $this->layout()->content ?>
</body>
</html>
