<?= $this->doctype(Zend_View_Helper_Doctype::XHTML1_STRICT) ?>
<html>
<head>
    <?= $this->headTitle() ?>

    <!-- Standard reset and fonts -->
    <link rel="stylesheet" type="text/css" href="/yui/build/reset/reset.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/calendar/assets/skins/sam/calendar.css" />
    <link rel="stylesheet" type="text/css" href="/yui/build/fonts/fonts-min.css">
    <link rel="stylesheet" type="text/css" href="/yui/build/container/assets/skins/sam/container.css">
	<link rel="stylesheet" type="text/css" href="/yui/build/datatable/assets/skins/sam/datatable.css" />

	
    <!-- CSS for Menu -->
    <link rel="stylesheet" type="text/css" href="/yui/build/menu/assets/skins/sam/menu.css"> 
    <link rel="stylesheet" href="/css/user.css" type="text/css" media="screen,projection"/>

    <!-- Dependency source files -->
    <script type="text/javascript" src="/yui/build/utilities/utilities.js"></script>
    <script type="text/javascript" src="/yui/build/container/container.js"></script>
	<script type="text/javascript" src="/yui/build/yahoo-dom-event/yahoo-dom-event.js"></script>
	<script type="text/javascript" src="/yui/build/element/element-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datasource/datasource-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/datatable/datatable-beta-min.js"></script>
	<script type="text/javascript" src="/yui/build/calendar/calendar-min.js"></script>

    <script type="text/javascript" src="/js/handlers.js"></script>
    <script type="text/javascript" src="/js/txtmenus.js"></script>
    <script type="text/javascript" src="/js/ajax.js"></script>
    <!-- Menu source file -->
    <script type="text/javascript" src="/yui/build/menu/menu.js"></script>
    <script type="text/javascript">
        YAHOO.util.Event.onDOMReady(function () {
            var oMenuBar = new YAHOO.widget.MenuBar("mymenubar", { 
                                                        lazyload: true,
                                                        itemdata: txtmenuspa
                                                        });
            oMenuBar.render(document.body);

            function onSubmenuShow() 
            {
                var oIFrame, oElement, nOffsetWidth;
                // Keep the left-most submenu against the left edge of the browser viewport
                if (this.id == "yahoo")
                {
                    YAHOO.util.Dom.setX(this.element, 0);
                    oIFrame = this.iframe;
                    if (oIFrame) 
                    {
                        YAHOO.util.Dom.setX(oIFrame, 0);
                    }
                    this.cfg.setProperty("x", 0, true);
                }

                if ((this.id == "filemenu" || this.id == "editmenu") && YAHOO.env.ua.ie)
                {
                    oElement = this.element;
                    nOffsetWidth = oElement.offsetWidth;
                    oElement.style.width = nOffsetWidth + "px";
                    oElement.style.width = (nOffsetWidth - (oElement.offsetWidth - nOffsetWidth)) + "px";
                }
            }
            oMenuBar.subscribe("show", onSubmenuShow);
        });
    </script>

    </head>
    <body class="yui-skin-sam">
    <?= $this->layout()->content ?>
    </body>
</html>
