<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->transporteSearchForm ?>
</div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr><th><?= $this->language->_("Bandera")?></th> <th><?= $this->language->_("Medio")?></th> <th><?= $this->language->_("Nombre")?></th> <th><?= $this->language->_("Observaciones")?></th> <th><?= $this->language->_("Modificar")?></th> <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $tran) { ?>
        <tr>
            <td> <?= $tran->name() ?> </td>
            <td> <?= $tran->codBanderaName() ?> </td>
            <td> <?= $tran->codMedioName() ?> </td>
            <td> <?= $tran->observaciones() ?> </td>
            <td>
                <a href="<?= "/user/transportes/modtransportes/id/" . $tran->id() ?>">Modificar</a>
            </td>
            <td>
                <a href="<?= "/user/transportes/removetransportes/id/" . $tran->id() ?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<script type="text/javascript">
YAHOO.util.Event.addListener(window, "load", function() {
    YAHOO.example.EnhanceFromMarkup = new function() {
        var myColumnDefs = [
            {key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
        {key:"flags",label:"<?= $this->language->_("Bandera")?>",sortable:true},
        {key:"medio",label:"<?= $this->language->_("Medio")?>", sortable:true},
        {key:"obs",label:"<?= $this->language->_("Observaciones")?>", sortable:false},
        {key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
        {key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}
        ];

        this.myDataSource = new YAHOO.util.DataSource(YAHOO.util.Dom.get("tablelist"));
        this.myDataSource.responseType = YAHOO.util.DataSource.TYPE_HTMLTABLE;
        this.myDataSource.responseSchema = {
            fields: [{key:"name"},
					{key:"flags"},
					{key:"medio"},
					{key:"obs"},
					{key:"mod"},
					{key:"elim"}]
	        };

        this.myDataTable = new YAHOO.widget.DataTable("divlistado", myColumnDefs, this.myDataSource,
                {sortedBy:{key:"name",dir:"desc"},draggableColumns:true}
        );
    };
});
</script>
