<? if (isset($this->error)) { ?>
    <div class="error_fatal"><?= $this->escape($this->error) ?></div>
    <div id="errmsg"></div>
    <script languaje="javascript">
        var time=0;
        showAlert("errmsg", { width:"620px", modal:true, visible:true, underlay:"shadow", fixedcenter:true, constraintoviewport:true, draggable:false } , "Error Fatal", "<div id='diverror' class='error_fatal'><?= $this->escape($this->language->_($this->error)) ?></div><br><div id='idtimeerror'></div>", "Trifiori");
        setInterval (function (){if (time==5){document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando al Home...'))?>";window.location.href = "/";}else{ document.getElementById('idtimeerror').innerHTML = "<?= $this->escape($this->language->_('Redireccionando en'))?> " + (5-time); time++;}}, 1000);
    </script>
<? } else { ?>
<!-- queda en el php las cosas a traducir -->
<script type="text/javascript">
var myColumnDefs = [
	{key:"name",label:"<?= $this->escape($this->language->_("Nombre"))?> <?= $this->sortby == 'name' ? '<img src=\'/images/sort' . $this->sort . '.gif\' width=\'10\' height=\'10\'>' : '' ?>", sortable:false},
	{key:"flags",label:"<?= $this->escape($this->language->_("Bandera"))?> <?= $this->sortby == 'flags' ? '<img src=\'/images/sort' . $this->sort . '.gif\' width=\'10\' height=\'10\'>' : '' ?>",sortable:false},
	{key:"medio",label:"<?= $this->escape($this->language->_("Medio"))?> <?= $this->sortby == 'medio' ? '<img src=\'/images/sort' . $this->sort . '.gif\' width=\'10\' height=\'10\'>' : '' ?>", sortable:false},
	{key:"obs",label:"<?= $this->escape($this->language->_("Observaciones"))?> <?= $this->sortby == 'obs' ? '<img src=\'/images/sort' . $this->sort . '.gif\' width=\'10\' height=\'10\'>' : '' ?>", sortable:false},
	{key:"mod",label:"<?= $this->escape($this->language->_("Modificar"))?>", sortable:false},
	{key:"elim",label:"<?= $this->escape($this->language->_("Eliminar"))?>", sortable:false}];

var hideLabel = "<?= $this->escape($this->language->_("Oculto"))?>";
var showLabel = "<?= $this->escape($this->language->_("Visible"))?>";
var closeLabel = "<?= $this->escape($this->language->_("Cerrar"))?>";
</script>
<script type="text/javascript" src="/js/init_listtransportes.js"></script>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $this->escape($msg) ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->transporteSearchForm ?>
</div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->escape($this->language->_("Opciones de la tabla"))?></a></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr><th><?= $this->escape($this->language->_("Bandera"))?></th> <th><?= $this->escape($this->language->_("Medio"))?></th> <th><?= $this->escape($this->language->_("Nombre"))?></th> <th><?= $this->escape($this->language->_("Observaciones"))?></th> <th><?= $this->escape($this->language->_("Modificar"))?></th> <th><?= $this->escape($this->language->_("Eliminar"))?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $tran) { ?>
        <tr>
            <td> <?= $this->escape($tran->name()) ?> </td>
            <td> <?= $this->escape($tran->codBanderaName()) ?> </td>
            <td> <?= $this->escape($tran->codMedioName()) ?> </td>
            <td> <?= $this->escape($tran->observaciones()) ?> </td>
            <td>
                <a href="<?= "/user/transportes/modtransportes/id/" . $this->escape($tran->id()) ?>"><img src="/images/modificar.png" alt="<?= $this->escape($this->language->_("Modificar"))?>" title="<?= $this->escape($this->language->_("Modificar"))?>" width="30" height="30"></a>
            </td>
            <td>
                <a href="<?= "/user/transportes/removetransportes/id/" . $this->escape($tran->id()) ?>"><img src="/images/borrar.png" alt="<?= $this->escape($this->language->_("Eliminar"))?>" title="<?= $this->escape($this->language->_("Eliminar"))?>" width="30" height="30"></a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->escape($this->language->_("Seleccione las columnas que desea ver:"))?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>
<? } ?>
