<!-- queda en el php las cosas a traducir -->
<script type="text/javascript">
var myColumnDefs = [
	{key:"name",label:"<?= $this->language->_("Nombre")?>", sortable:true},
	{key:"flags",label:"<?= $this->language->_("Bandera")?>",sortable:true},
	{key:"medio",label:"<?= $this->language->_("Medio")?>", sortable:true},
	{key:"obs",label:"<?= $this->language->_("Observaciones")?>", sortable:false},
	{key:"mod",label:"<?= $this->language->_("Modificar")?>", sortable:false},
	{key:"elim",label:"<?= $this->language->_("Eliminar")?>", sortable:false}];

var hideLabel = "<?= $this->language->_("Oculto")?>";
var showLabel = "<?= $this->language->_("Visible")?>";
var closeLabel = "<?= $this->language->_("Cerrar")?>";
</script>
<script type="text/javascript" src="/js/init_listtransportes.js"></script>

<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
            <? } ?>
            <? if (isset($this->message)) { ?>
                <? foreach ($this->message as $msg) { ?>
                    <div class="msg"><?= $msg ?></div>
                            <? } ?>
                            <? } ?>
<div class="busqueda">
    <?= $this->transporteSearchForm ?>
</div>
<div><a id="dt-options-link" href="fallbacklink.html"><?= $this->language->_("Opciones de la tabla")?></a></div>
<div id="divlistado" class="clistado">
	<table id="tablelist">
    <thead>
        <tr><th><?= $this->language->_("Bandera")?></th> <th><?= $this->language->_("Medio")?></th> <th><?= $this->language->_("Nombre")?></th> <th><?= $this->language->_("Observaciones")?></th> <th><?= $this->language->_("Modificar")?></th> <th><?= $this->language->_("Eliminar")?></th></tr>
    </thead>
    <tbody>
    <? if (count($this->paginator)) { ?>
        <? foreach($this->paginator as $tran) { ?>
        <tr>
            <td> <?= $tran->name() ?> </td>
            <td> <?= $tran->codBanderaName() ?> </td>
            <td> <?= $tran->codMedioName() ?> </td>
            <td> <?= $tran->observaciones() ?> </td>
            <td>
                <a href="<?= "/user/transportes/modtransportes/id/" . $tran->id() ?>">Modificar</a>
            </td>
            <td>
                <a href="<?= "/user/transportes/removetransportes/id/" . $tran->id() ?>">Eliminar</a>
            </td>
        </tr>
        <? } ?>
    <? } ?>
    </tbody>
</table>
</div>

<?php if (count($this->paginator)) { ?>
    <?= $this->paginationControl($this->paginator, 'Sliding', 'paginationControl.phtml'); ?>
<?php } ?>

<div id="columnshowhide"></div>

<div id="dt-dlg">
    <span class="corner_tr"></span>
    <span class="corner_tl"></span>
    <span class="corner_br"></span>
    <span class="corner_bl"></span>
    <div class="hd">
        <?= $this->language->_("Seleccione las columnas que desea ver:")?>
    </div>
    <div id="dt-dlg-picker" class="bd">
    </div>
</div>

