<? if (isset($this->error)) { ?>
    <div class="error"><?= $this->error ?></div>
<? } ?>
<div class="cformulario">
	<?= $this->transporteModForm ?>
</div>
<div id='form_errorloc' class='errors_js_forms'></div>
<script type="text/javascript">

	var mySchema = ["Resultset.Result","data","id"];

	// banderas
        var dataBanderas = new YAHOO.widget.DS_XHR("/user/banderas/getdata/", mySchema);
        dataBanderas.responseType = YAHOO.widget.DS_XHR.TYPE_JSON;
        var autocompleteBanderas = new YAHOO.widget.AutoComplete("idnameBandera", "idbanderasautocomplete", dataBanderas);

	// validacion
	var frmvalidator  = new Validator("form");

	//habilito alert con mensajes
	frmvalidator.EnableOnPageErrorDisplaySingleBox();
	frmvalidator.EnableMsgsTogether();

	frmvalidator.addValidation("name","req","<?= $this->language->_("*Ingrese un nombre")?>");
	frmvalidator.addValidation("name","alnum_s ","<?= $this->language->_("*El nombre debe ser alfanumérico")?>");
	frmvalidator.addValidation("name","maxlen=20","<?= $this->language->_("*El nombre debe contener hasta 20 caracteres")?>");

	frmvalidator.addValidation("codBandera","req","<?= $this->language->_("*Seleccione una bandera")?>");

	frmvalidator.addValidation("codMedio","req","<?= $this->language->_("*Seleccione un medio")?>");
</script>